// GENERATED by canon: C++ runtime rt_v1 (JSON). DO NOT EDIT.
#ifndef CANON_RUNTIME_JSON_RT_V1
#define CANON_RUNTIME_JSON_RT_V1

#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <fstream>
#include <iterator>
#include <limits>
#include <optional>
#include <set>
#include <string>
#include <string_view>
#include <type_traits>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "canon_runtime.h"

namespace canon {
inline namespace rt_v1 {
namespace json {

using Json = nlohmann::json;

/// Reads the whole file. False (with `error` set) when it cannot be read.
inline bool ReadFile(const std::string& path, std::string& out, std::string& error) {
    std::ifstream in(path, std::ios::binary);
    if (!in) {
        error = "cannot open " + path;
        return false;
    }
    out.assign(std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>());
    if (in.bad()) {
        error = "cannot read " + path;
        return false;
    }
    return true;
}

/// The deepest nesting of arrays and objects a data file may hold (WIRE.md §3.1).
inline constexpr size_t kMaxNesting = 512;

/// The largest Duration in milliseconds, either sign (TYPES.md §7.2).
inline constexpr int64_t kDurationMaxMs = 9223372036854;

/// The smallest magnitude a Float32 rounds to infinity from: a number that large is refused.
inline constexpr double kFloat32Overflow = 3.4028235677973366e+38;

/// True when `a` and `b` are equal ignoring the case of ASCII letters, and only of them. A
/// generated loader refuses a key that matches an expected one only this way.
inline bool EqualFold(std::string_view a, std::string_view b) {
    if (a.size() != b.size()) return false;
    for (size_t i = 0; i < a.size(); ++i) {
        const char x = a[i] >= 'A' && a[i] <= 'Z' ? static_cast<char>(a[i] - 'A' + 'a') : a[i];
        const char y = b[i] >= 'A' && b[i] <= 'Z' ? static_cast<char>(b[i] - 'A' + 'a') : b[i];
        if (x != y) return false;
    }
    return true;
}

namespace detail {

/// What an integer outside [lo, hi] is told: "expected an integer", with the range unless it
/// is Int's.
inline std::string IntExpected(int64_t lo, int64_t hi) {
    if (lo == kIntMin && hi == kIntMax) return "expected an integer";
    return "expected an integer from " + std::to_string(lo) + " to " + std::to_string(hi);
}

}  // namespace detail

/// A SAX pass over a data file before it is parsed: the file is one object, no object holds a
/// key twice (nlohmann would keep the last), and nothing nests deeper than kMaxNesting. It stops
/// at the first finding and names its path ("rows[3].id: duplicate key").
class StrictCheck {
public:
    bool null() { return Value(); }
    bool boolean(bool) { return Value(); }
    bool number_integer(Json::number_integer_t) { return Value(); }
    bool number_unsigned(Json::number_unsigned_t) { return Value(); }
    bool number_float(Json::number_float_t, const Json::string_t&) { return Value(); }
    bool string(Json::string_t&) { return Value(); }
    bool binary(Json::binary_t&) { return Value(); }
    bool start_object(size_t) { return Open(true); }
    bool start_array(size_t) { return Open(false); }
    bool end_object() { return frames_.pop_back(), true; }
    bool end_array() { return frames_.pop_back(), true; }
    bool key(Json::string_t& name) {
        Frame& f = frames_.back();
        f.key = name;
        if (f.keys.insert(name).second) return true;
        return Refuse("duplicate key");
    }
    bool parse_error(size_t, const std::string&, const Json::exception&) { return false; }

    /// Empty unless the pass found a duplicate key or a nesting too deep.
    const std::string& Error() const noexcept { return error_; }

private:
    struct Frame {
        bool object = false;
        size_t next = 0;           // an array's elements started so far
        std::string key;           // an object's last key
        std::set<std::string> keys;
    };

    bool Value() {
        if (frames_.empty()) return false;
        if (!frames_.back().object) ++frames_.back().next;
        return true;
    }

    bool Open(bool object) {
        if (frames_.empty() && !object) return false;
        if (!frames_.empty() && !Value()) return false;
        if (frames_.size() >= kMaxNesting) {
            return Refuse("nested deeper than " + std::to_string(kMaxNesting) + " levels");
        }
        frames_.emplace_back();
        frames_.back().object = object;
        return true;
    }

    /// The path of the value being read, then what is wrong with it.
    bool Refuse(const std::string& what) {
        for (const Frame& f : frames_) {
            if (f.object) {
                if (!error_.empty()) error_ += '.';
                error_ += f.key;
            } else {
                error_ += '[' + std::to_string(f.next - 1) + ']';
            }
        }
        error_ += ": " + what;
        return false;
    }

    std::vector<Frame> frames_;
    std::string error_;
};

/// Parses a data file written by `canon build` and checks its "$schema" against the
/// fingerprint compiled into this binary. `name` is used in messages (a path, or
/// "embedded potions.json"). The envelope's keys ("$schema", "rows", "value", "$fns") match
/// exactly: one differing only in letter case is refused, as StrictCheck's findings are.
inline bool ParseDataFile(const std::string& name, const std::string& text, std::string_view schema,
                          Json& doc, std::string& error) {
    StrictCheck check;
    const bool strict = Json::sax_parse(text, &check);
    if (!check.Error().empty()) {
        error = name + ": " + check.Error();
        return false;
    }
    if (strict) doc = Json::parse(text, nullptr, /*allow_exceptions=*/false);
    if (!strict || doc.is_discarded() || !doc.is_object()) {
        error = name + ": not a canon data file (invalid JSON)";
        return false;
    }
    for (const auto& item : doc.items()) {
        for (const char* key : {"$fns", "$schema", "rows", "value"}) {
            if (item.key() != key && EqualFold(item.key(), key)) {
                error = name + ": " + item.key() + ": differs from \"" + key + "\" only in letter case";
                return false;
            }
        }
    }
    auto it = doc.find("$schema");
    std::string got = "<none>";
    if (it != doc.end() && it->is_string()) got = it->get_ref<const std::string&>();
    if (got != schema) {
        error = name + ": built from schema " + got + ", this binary expects " + std::string(schema) +
                ". Rebuild the data or deploy the matching binary";
        return false;
    }
    return true;
}

/// Reads JSON values into generated classes. It records the first error with the
/// path of the value, and never validates: values were checked by `canon build`.
class Decoder {
public:
    explicit Decoder(std::string name) : name_(std::move(name)) {}

    bool Ok() const noexcept { return error_.empty(); }
    const std::string& Error() const noexcept { return error_; }

    /// Path tracking for messages: Push("rows[3]") ... Pop().
    void Push(std::string segment) { path_.push_back(std::move(segment)); }
    void Pop() { path_.pop_back(); }

    /// Records an error at the current path (only the first one is kept).
    void Fail(std::string_view key, std::string_view what) {
        if (!error_.empty()) return;
        error_ = name_ + ": ";
        for (size_t i = 0; i < path_.size(); ++i) {
            if (i > 0) error_ += '.';
            error_ += path_[i];
        }
        if (!key.empty()) {
            if (!path_.empty()) error_ += '.';
            error_ += key;
        }
        error_ += ": ";
        error_ += what;
    }

    /// The value of `key`, or nullptr when the key is absent or null.
    const Json* Optional(const Json& obj, const char* key) {
        if (!obj.is_object()) {
            Fail(key, "expected an object");
            return nullptr;
        }
        auto it = obj.find(key);
        if (it == obj.end() || it->is_null()) return nullptr;
        return &*it;
    }

    /// The value of `key`; an error when it is absent ("missing") or null ("null").
    const Json* Required(const Json& obj, const char* key) {
        if (!obj.is_object()) return Fail(key, "expected an object"), nullptr;
        auto it = obj.find(key);
        if (it == obj.end()) return Fail(key, "missing"), nullptr;
        if (it->is_null()) return Fail(key, "null"), nullptr;
        return &*it;
    }

    bool AsString(const Json& v, std::string_view key, std::string& out) {
        if (!v.is_string()) return Fail(key, "expected a string"), false;
        out = v.get_ref<const std::string&>();
        return true;
    }

    bool AsInt(const Json& v, std::string_view key, int64_t& out) { return AsIntIn(v, key, kIntMin, kIntMax, out); }

    /// An integer token from `lo` to `hi`; anything else fails with detail::IntExpected.
    bool AsIntIn(const Json& v, std::string_view key, int64_t lo, int64_t hi, int64_t& out) {
        bool ok = v.is_number_integer();
        int64_t n = 0;
        if (v.is_number_unsigned()) {
            ok = v.get<uint64_t>() <= static_cast<uint64_t>(kIntMax);
            if (ok) n = static_cast<int64_t>(v.get<uint64_t>());
        } else if (ok) {
            n = v.get<int64_t>();
        }
        if (!ok || n < lo || n > hi) return Fail(key, detail::IntExpected(lo, hi)), false;
        out = n;
        return true;
    }

    /// A Float may be written as an integer token ("1" for 1.0).
    bool AsFloat(const Json& v, std::string_view key, double& out) {
        if (!v.is_number()) return Fail(key, "expected a number"), false;
        out = v.get<double>();
        return true;
    }

    /// A Float32: any number whose magnitude does not round to infinity.
    bool AsFloat32(const Json& v, std::string_view key, float& out) {
        if (!v.is_number() || std::fabs(v.get<double>()) >= kFloat32Overflow) {
            return Fail(key, "expected a number that fits Float32"), false;
        }
        out = static_cast<float>(v.get<double>());
        return true;
    }

    bool AsBool(const Json& v, std::string_view key, bool& out) {
        if (!v.is_boolean()) return Fail(key, "expected true or false"), false;
        out = v.get<bool>();
        return true;
    }

    /// `unitMs` is the length of one wire unit: 1 for ms, 1000 for s, 60000 for m... The count
    /// must keep the Duration within kDurationMaxMs.
    bool AsDuration(const Json& v, std::string_view key, int64_t unitMs, std::chrono::milliseconds& out) {
        const int64_t limit = kDurationMaxMs / unitMs;
        int64_t n = 0;
        if (!AsIntIn(v, key, -limit, limit, n)) return false;
        out = std::chrono::milliseconds(n * unitMs);
        return true;
    }

    /// `parse` is a generated <Enum>FromWire (a string) or <Enum>FromCode (an integer within the
    /// code type, UInt64's capped at Int's maximum) function.
    template <class E, class W>
    bool AsEnum(const Json& v, std::string_view key, std::optional<E> (*parse)(W), E& out) {
        std::optional<E> e;
        std::string wire;
        if constexpr (std::is_same_v<W, std::string_view>) {
            if (!AsString(v, key, wire)) return false;
            e = parse(std::string_view(wire));
        } else {
            constexpr int64_t lo = std::is_signed_v<W> ? static_cast<int64_t>(std::numeric_limits<W>::min()) : 0;
            constexpr bool wide = static_cast<uint64_t>(std::numeric_limits<W>::max()) > static_cast<uint64_t>(kIntMax);
            constexpr int64_t hi = wide ? kIntMax : static_cast<int64_t>(std::numeric_limits<W>::max());
            int64_t n = 0;
            if (!AsIntIn(v, key, lo, hi, n)) return false;
            e = parse(static_cast<W>(n));
            wire = std::to_string(n);
        }
        if (!e) return Fail(key, "unknown value " + wire), false;
        out = *e;
        return true;
    }

    /// The array at `key` (or nullptr with an error).
    const Json* Array(const Json& obj, const char* key) {
        const Json* v = Required(obj, key);
        if (v != nullptr && !v->is_array()) return Fail(key, "expected an array"), nullptr;
        return v;
    }

    /// The object at `key` (or nullptr with an error).
    const Json* Object(const Json& obj, const char* key) {
        const Json* v = Required(obj, key);
        if (v != nullptr && !v->is_object()) return Fail(key, "expected an object"), nullptr;
        return v;
    }

    // Field shortcuts: Required + As*.
    bool String(const Json& obj, const char* key, std::string& out) {
        const Json* v = Required(obj, key);
        return v != nullptr && AsString(*v, key, out);
    }
    bool Int(const Json& obj, const char* key, int64_t& out) {
        const Json* v = Required(obj, key);
        return v != nullptr && AsInt(*v, key, out);
    }
    bool Float(const Json& obj, const char* key, double& out) {
        const Json* v = Required(obj, key);
        return v != nullptr && AsFloat(*v, key, out);
    }
    bool Bool(const Json& obj, const char* key, bool& out) {
        const Json* v = Required(obj, key);
        return v != nullptr && AsBool(*v, key, out);
    }
    bool Duration(const Json& obj, const char* key, int64_t unitMs, std::chrono::milliseconds& out) {
        const Json* v = Required(obj, key);
        return v != nullptr && AsDuration(*v, key, unitMs, out);
    }
    template <class E, class W>
    bool Enum(const Json& obj, const char* key, std::optional<E> (*parse)(W), E& out) {
        const Json* v = Required(obj, key);
        return v != nullptr && AsEnum(*v, key, parse, out);
    }

private:
    std::string name_;
    std::vector<std::string> path_;
    std::string error_;
};

namespace detail {

/// True when `v` is an object; else "null" or "expected an object" at the decoder's path.
inline bool Object(const Json& v, Decoder& dec) {
    if (v.is_object()) return true;
    dec.Fail(std::string_view(), v.is_null() ? "null" : "expected an object");
    return false;
}

/// Object, then refuses a key of `v` that is none of `keys` (sorted in byte order) and differs
/// from one only in letter case: the first in the object's order, the smallest in byte order.
template <size_t N>
bool Keys(const Json& v, Decoder& dec, const char* const (&keys)[N]) {
    if (!Object(v, dec)) return false;
    const auto less = [](const char* k, std::string_view s) { return std::string_view(k) < s; };
    for (const auto& item : v.items()) {
        const std::string& key = item.key();
        const auto it = std::lower_bound(std::begin(keys), std::end(keys), std::string_view(key), less);
        if (it != std::end(keys) && key == *it) continue;
        for (const char* k : keys) {
            if (EqualFold(key, k)) {
                dec.Fail(key, "differs from \"" + std::string(k) + "\" only in letter case");
                return false;
            }
        }
    }
    return true;
}

/// A lookup cell (WIRE.md §5.11): absent fails; null is none (nullptr) when `optional`, else fails.
inline const Json* Cell(const Json& obj, Decoder& dec, const char* key, bool optional) {
    const auto it = obj.find(key);
    if (it == obj.end()) return dec.Fail(key, "missing"), nullptr;
    if (!it->is_null()) return &*it;
    if (!optional) dec.Fail(key, "null");
    return nullptr;
}

/// A table row's `$id`, and its `$retired`, which must be true when present (WIRE.md §5.7).
inline void Row(const Json& row, Decoder& dec, std::string& id, bool& retired) {
    if (!Object(row, dec)) return;
    const char* const idKey = "$id";
    const char* const retiredKey = "$retired";
    if (const Json* x = dec.Required(row, idKey)) dec.AsString(*x, idKey, id);
    const auto it = row.find(retiredKey);
    if (it == row.end()) return;
    if (it->is_boolean() && it->get<bool>()) {
        retired = true;
    } else {
        dec.Fail(retiredKey, "expected true");
    }
}

/// The object at a path's intermediate key (WIRE.md §5.5.3): nullptr when absent; null or
/// another kind fails.
inline const Json* Step(const Json& obj, Decoder& dec, const char* key) {
    const auto it = obj.find(key);
    if (it == obj.end()) return nullptr;
    if (it->is_object()) return &*it;
    dec.Fail(key, it->is_null() ? "null" : "expected an object");
    return nullptr;
}

/// Pairs slot `k`, `val` of `v` (WIRE.md §5.14): false for an empty slot, which sets `empty`, and
/// for a bad one, reported at the slot's first key present.
inline bool Slot(const Json& v, Decoder& dec, const char* k, const char* val, bool& empty) {
    const auto kt = v.find(k), vt = v.find(val);
    const bool hasK = kt != v.end(), hasV = vt != v.end();
    if (!hasK && !hasV) {
        empty = true;
        return false;
    }
    const char* first = hasK ? k : val;
    if (hasK != hasV) {
        dec.Fail(first, "incomplete pairs slot");
    } else if (kt->is_null() || vt->is_null()) {
        dec.Fail(first, "null in a pairs slot");
    } else if (empty) {
        dec.Fail(first, "pairs slot after an empty one");
    }
    return dec.Ok();
}

/// A `bits` value (WIRE.md §5.3): a non-negative integer with no bit outside `mask`.
inline bool Bits(const Json& x, Decoder& dec, std::string_view key, uint64_t mask, uint64_t& out) {
    int64_t n = 0;
    if (!dec.AsIntIn(x, key, 0, kIntMax, n)) return false;
    out = static_cast<uint64_t>(n);
    std::string hex;
    for (uint64_t rest = out & ~mask; rest != 0; rest >>= 4) hex.insert(hex.begin(), "0123456789abcdef"[rest & 15]);
    if (hex.empty()) return true;
    dec.Fail(key, "unknown bits 0x" + hex);
    return false;
}

}  // namespace detail

}  // namespace json
}  // namespace rt_v1
}  // namespace canon

#endif  // CANON_RUNTIME_JSON_RT_V1
