// GENERATED by canon: C++ runtime rt_v1. DO NOT EDIT.
//
// Helpers shared by every C++ file canon generates into this directory. The file is
// identical in every output directory that uses runtime version 1, and everything in
// it lives in namespace canon::rt_v1, so two output directories linked into one
// binary never break the one-definition rule. It depends only on the standard library.
#ifndef CANON_RUNTIME_RT_V1
#define CANON_RUNTIME_RT_V1

#include <algorithm>
#include <atomic>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <limits>
#include <memory>
#include <string>
#include <string_view>
#include <type_traits>
#include <utility>
#include <vector>

namespace canon {
inline namespace rt_v1 {

namespace json {
class Decoder;  // canon_runtime_json.h
}  // namespace json

// ---------------------------------------------------------------------------
// Evaluation errors (DECISIONS 19). Generated code never throws.
// ---------------------------------------------------------------------------

/// Called when translated code hits an error the Canon evaluator would report
/// (overflow, division by zero, ...). `code` is the Canon diagnostic code ("E4101");
/// both views point to string literals.
using EvalErrorHandler = void (*)(std::string_view code, std::string_view message);

namespace detail {
inline void DefaultEvalErrorHandler(std::string_view code, std::string_view message) {
    std::fprintf(stderr, "canon: evaluation error %.*s: %.*s\n", static_cast<int>(code.size()),
                 code.data(), static_cast<int>(message.size()), message.data());
    std::fflush(stderr);
    std::abort();
}
inline std::atomic<EvalErrorHandler> g_evalErrorHandler{&DefaultEvalErrorHandler};
}  // namespace detail

/// Replaces the handler and returns the previous one. nullptr restores the default,
/// which prints the error to stderr and calls std::abort().
inline EvalErrorHandler SetEvalErrorHandler(EvalErrorHandler handler) noexcept {
    return detail::g_evalErrorHandler.exchange(handler != nullptr ? handler
                                                                  : &detail::DefaultEvalErrorHandler);
}

/// Reports an evaluation error. If the handler returns, the helper that called it
/// returns 0 (or 0.0) and the translated function carries on with that value.
inline void OnEvalError(std::string_view code, std::string_view message) {
    detail::g_evalErrorHandler.load()(code, message);
}

// ---------------------------------------------------------------------------
// Checked arithmetic (CONFORMANCE.md §3). Int is int64_t, Float is double,
// Duration is int64_t milliseconds.
// ---------------------------------------------------------------------------

inline constexpr int64_t kIntMin = std::numeric_limits<int64_t>::min();
inline constexpr int64_t kIntMax = std::numeric_limits<int64_t>::max();

inline int64_t AddInt(int64_t a, int64_t b) {
    if ((b > 0 && a > kIntMax - b) || (b < 0 && a < kIntMin - b)) {
        OnEvalError("E4101", "integer overflow in +");
        return 0;
    }
    return a + b;
}

inline int64_t SubInt(int64_t a, int64_t b) {
    if ((b < 0 && a > kIntMax + b) || (b > 0 && a < kIntMin + b)) {
        OnEvalError("E4101", "integer overflow in -");
        return 0;
    }
    return a - b;
}

inline int64_t MulInt(int64_t a, int64_t b) {
    bool overflow;
    if (a > 0) {
        overflow = b > 0 ? a > kIntMax / b : b < kIntMin / a;
    } else {
        overflow = b > 0 ? a < kIntMin / b : (a != 0 && b < kIntMax / a);
    }
    if (overflow) {
        OnEvalError("E4101", "integer overflow in *");
        return 0;
    }
    return a * b;
}

inline int64_t DivInt(int64_t a, int64_t b) {
    if (b == 0) {
        OnEvalError("E4102", "integer division by zero");
        return 0;
    }
    if (a == kIntMin && b == -1) {
        OnEvalError("E4101", "integer overflow in /");
        return 0;
    }
    return a / b;
}

inline int64_t ModInt(int64_t a, int64_t b) {
    if (b == 0) {
        OnEvalError("E4102", "integer division by zero in %");
        return 0;
    }
    if (b == -1) return 0;
    return a % b;
}

inline int64_t NegInt(int64_t a) {
    if (a == kIntMin) {
        OnEvalError("E4101", "integer overflow in unary -");
        return 0;
    }
    return -a;
}

inline int64_t AbsInt(int64_t a) {
    if (a == kIntMin) {
        OnEvalError("E4101", "integer overflow in abs");
        return 0;
    }
    return a < 0 ? -a : a;
}

inline int64_t MinInt(int64_t a, int64_t b) { return (std::min)(a, b); }
inline int64_t MaxInt(int64_t a, int64_t b) { return (std::max)(a, b); }

inline int64_t ClampInt(int64_t x, int64_t lo, int64_t hi) {
    if (lo > hi) {
        OnEvalError("E4108", "clamp with lo > hi");
        return 0;
    }
    return x < lo ? lo : (x > hi ? hi : x);
}

/// Any Float operation whose result is NaN or infinite is E4104.
inline double CheckFloat(double x) {
    if (!std::isfinite(x)) {
        OnEvalError("E4104", "float result is not finite");
        return 0.0;
    }
    return x;
}

inline double AddFloat(double a, double b) { return CheckFloat(a + b); }
inline double SubFloat(double a, double b) { return CheckFloat(a - b); }
inline double MulFloat(double a, double b) { return CheckFloat(a * b); }
inline double DivFloat(double a, double b) { return CheckFloat(a / b); }
inline double ModFloat(double a, double b) { return CheckFloat(std::fmod(a, b)); }
inline double NegFloat(double a) { return -a; }
inline double AbsFloat(double a) { return std::fabs(a); }

/// min and max order -0.0 before +0.0 (IEEE 754-2019 minimum and maximum).
inline double MinFloat(double a, double b) {
    if (a < b) return a;
    if (b < a) return b;
    return std::signbit(a) ? a : b;
}

inline double MaxFloat(double a, double b) {
    if (a > b) return a;
    if (b > a) return b;
    return std::signbit(a) ? b : a;
}

inline double ClampFloat(double x, double lo, double hi) {
    if (lo > hi) {
        OnEvalError("E4108", "clamp with lo > hi");
        return 0.0;
    }
    return MinFloat(MaxFloat(x, lo), hi);
}

inline double IntToFloat(int64_t i) { return static_cast<double>(i); }

/// Int(f): truncates toward zero; E4103 when the result does not fit.
inline int64_t FloatToInt(double f) {
    if (!(f >= -9223372036854775808.0 && f < 9223372036854775808.0)) {
        OnEvalError("E4103", "float out of the Int range");
        return 0;
    }
    return static_cast<int64_t>(f);
}

inline int64_t FloorFloat(double f) { return FloatToInt(std::floor(f)); }
inline int64_t CeilFloat(double f) { return FloatToInt(std::ceil(f)); }
/// Rounds half away from zero.
inline int64_t RoundFloat(double f) { return FloatToInt(std::round(f)); }

/// Duration / Duration is a Float; a zero divisor is E4102.
inline double DivDuration(int64_t a, int64_t b) {
    if (b == 0) {
        OnEvalError("E4102", "duration division by zero");
        return 0.0;
    }
    return CheckFloat(static_cast<double>(a) / static_cast<double>(b));
}

/// Range refinement of a parameter or a return value (lo and hi inclusive): E3204.
inline int64_t CheckIntRange(int64_t v, int64_t lo, int64_t hi) {
    if (v < lo || v > hi) {
        OnEvalError("E3204", "value outside its refinement range");
        return 0;
    }
    return v;
}

inline double CheckFloatRange(double v, double lo, double hi) {
    if (v < lo || v > hi) {
        OnEvalError("E3204", "value outside its refinement range");
        return 0.0;
    }
    return v;
}

/// Range of a sized integer type (Int8 ... UInt64) of a parameter or a return value: E3201.
inline int64_t CheckIntWidth(int64_t v, int64_t lo, int64_t hi) {
    if (v < lo || v > hi) {
        OnEvalError("E3201", "value does not fit its sized integer type");
        return 0;
    }
    return v;
}

/// Stores a Float into a Float32, rounding to nearest-even; overflow is E3202.
inline float ToFloat32(double v) {
    if (std::fabs(v) >= 3.4028235677973366e+38) {
        OnEvalError("E3202", "value overflows Float32");
        return 0.0f;
    }
    return static_cast<float>(v);
}

/// A Float argument that is NaN or infinite is E4104 on entry.
inline double CheckFloatArg(double v) { return CheckFloat(v); }

// ---------------------------------------------------------------------------
// Read-only containers
// ---------------------------------------------------------------------------

/// The type a lookup takes: std::string_view for std::string keys, the key itself
/// otherwise. Lookups never allocate.
template <class K>
using LookupKey = std::conditional_t<std::is_same_v<K, std::string>, std::string_view, K>;

namespace detail {
template <class K>
LookupKey<K> AsLookup(const K& k) {
    return LookupKey<K>(k);
}

/// Positions of `keys`, sorted by key.
template <class K>
std::vector<uint32_t> SortedIndex(const std::vector<K>& keys) {
    std::vector<uint32_t> index(keys.size());
    for (uint32_t i = 0; i < index.size(); ++i) index[i] = i;
    std::sort(index.begin(), index.end(), [&keys](uint32_t a, uint32_t b) {
        return AsLookup(keys[a]) < AsLookup(keys[b]);
    });
    return index;
}

/// Binary search of `key` among `keys` through `index`; returns the position or -1.
template <class K>
std::ptrdiff_t FindSorted(const std::vector<K>& keys, const std::vector<uint32_t>& index,
                          LookupKey<K> key) {
    auto it = std::lower_bound(index.begin(), index.end(), key,
                               [&keys](uint32_t i, LookupKey<K> k) { return AsLookup(keys[i]) < k; });
    if (it == index.end() || !(AsLookup(keys[*it]) == key)) return -1;
    return static_cast<std::ptrdiff_t>(*it);
}
}  // namespace detail

/// A read-only map: iteration in source order, Find by binary search.
template <class K, class V>
class FlatMap {
public:
    using Entry = std::pair<K, V>;

    FlatMap() = default;

    /// For generated code: `entries` in source order, keys unique.
    static FlatMap FromEntries(std::vector<Entry> entries) {
        FlatMap m;
        m.entries_ = std::move(entries);
        m.keys_.reserve(m.entries_.size());
        for (const Entry& e : m.entries_) m.keys_.push_back(e.first);
        m.index_ = detail::SortedIndex(m.keys_);
        return m;
    }

    size_t Len() const noexcept { return entries_.size(); }
    const Entry& At(size_t i) const { return entries_[i]; }
    const std::vector<Entry>& All() const noexcept { return entries_; }
    typename std::vector<Entry>::const_iterator begin() const noexcept { return entries_.begin(); }
    typename std::vector<Entry>::const_iterator end() const noexcept { return entries_.end(); }

    /// nullptr when the key is absent.
    const V* Find(LookupKey<K> key) const {
        std::ptrdiff_t i = detail::FindSorted(keys_, index_, key);
        return i < 0 ? nullptr : &entries_[static_cast<size_t>(i)].second;
    }

private:
    std::vector<Entry> entries_;
    std::vector<K> keys_;
    std::vector<uint32_t> index_;
};

/// A read-only list whose elements are unique by a key: `[T] keyed by f` fields.
template <class K, class T>
class KeyedList {
public:
    KeyedList() = default;

    /// For generated code: `rows` in source order and their keys, keys unique.
    static KeyedList FromRows(std::vector<T> rows, std::vector<K> keys) {
        KeyedList l;
        l.rows_ = std::move(rows);
        l.keys_ = std::move(keys);
        l.index_ = detail::SortedIndex(l.keys_);
        return l;
    }

    size_t Len() const noexcept { return rows_.size(); }
    const T& At(size_t i) const { return rows_[i]; }
    const std::vector<T>& All() const noexcept { return rows_; }
    typename std::vector<T>::const_iterator begin() const noexcept { return rows_.begin(); }
    typename std::vector<T>::const_iterator end() const noexcept { return rows_.end(); }

    /// nullptr when the key is absent.
    const T* Find(LookupKey<K> key) const {
        std::ptrdiff_t i = detail::FindSorted(keys_, index_, key);
        return i < 0 ? nullptr : &rows_[static_cast<size_t>(i)];
    }

private:
    std::vector<T> rows_;
    std::vector<K> keys_;
    std::vector<uint32_t> index_;
};

// ---------------------------------------------------------------------------
// Snapshots (SPEC §15.5)
// ---------------------------------------------------------------------------

/// An atomically replaceable std::shared_ptr. Readers keep the snapshot they loaded;
/// the old one is freed when its last reader lets go.
template <class T>
class AtomicSharedPtr {
public:
    constexpr AtomicSharedPtr() noexcept = default;
    AtomicSharedPtr(const AtomicSharedPtr&) = delete;
    AtomicSharedPtr& operator=(const AtomicSharedPtr&) = delete;

#if defined(__cpp_lib_atomic_shared_ptr) && __cpp_lib_atomic_shared_ptr >= 201711L
    std::shared_ptr<T> Load() const noexcept { return p_.load(std::memory_order_acquire); }
    void Store(std::shared_ptr<T> p) noexcept { p_.store(std::move(p), std::memory_order_release); }

private:
    std::atomic<std::shared_ptr<T>> p_;
#else
    std::shared_ptr<T> Load() const noexcept {
        return std::atomic_load_explicit(&p_, std::memory_order_acquire);
    }
    void Store(std::shared_ptr<T> p) noexcept {
        std::atomic_store_explicit(&p_, std::move(p), std::memory_order_release);
    }

private:
    std::shared_ptr<T> p_;
#endif
};

}  // namespace rt_v1
}  // namespace canon

#endif  // CANON_RUNTIME_RT_V1
