// GENERATED by canon: C++ runtime rt_v1 (JSON). DO NOT EDIT.
//
// Helpers for the loaders and decoders of `data`, `embedded` and `types` mode.
// Requires nlohmann/json 3.9 or later. Nothing here throws: parsing uses
// allow_exceptions=false and every typed read checks the JSON type first, so the
// code also builds with exceptions disabled.
#ifndef CANON_RUNTIME_JSON_RT_V1
#define CANON_RUNTIME_JSON_RT_V1

#include <chrono>
#include <cstdint>
#include <fstream>
#include <iterator>
#include <optional>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "canon_runtime.h"

namespace canon {
inline namespace rt_v1 {
namespace json {

using Json = nlohmann::json;

/// Reads the whole file. False (with `error` set) when it cannot be read.
inline bool ReadFile(const std::string& path, std::string& out, std::string& error) {
    std::ifstream in(path, std::ios::binary);
    if (!in) {
        error = "cannot open " + path;
        return false;
    }
    out.assign(std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>());
    if (in.bad()) {
        error = "cannot read " + path;
        return false;
    }
    return true;
}

/// Parses a data file written by `canon build` and checks its "$schema" against the
/// fingerprint compiled into this binary. `name` is used in messages (a path, or
/// "embedded potions.json").
inline bool ParseDataFile(const std::string& name, const std::string& text, std::string_view schema,
                          Json& doc, std::string& error) {
    doc = Json::parse(text, nullptr, /*allow_exceptions=*/false);
    if (doc.is_discarded() || !doc.is_object()) {
        error = name + ": not a canon data file (invalid JSON)";
        return false;
    }
    auto it = doc.find("$schema");
    std::string got = "<none>";
    if (it != doc.end() && it->is_string()) got = it->get_ref<const std::string&>();
    if (got != schema) {
        error = name + ": built from schema " + got + ", this binary expects " + std::string(schema) +
                ". Rebuild the data or deploy the matching binary";
        return false;
    }
    return true;
}

/// Reads JSON values into generated classes. It records the first error with the
/// path of the value, and never validates: values were checked by `canon build`.
class Decoder {
public:
    explicit Decoder(std::string name) : name_(std::move(name)) {}

    bool Ok() const noexcept { return error_.empty(); }
    const std::string& Error() const noexcept { return error_; }

    /// Path tracking for messages: Push("rows[3]") ... Pop().
    void Push(std::string segment) { path_.push_back(std::move(segment)); }
    void Pop() { path_.pop_back(); }

    /// Records an error at the current path (only the first one is kept).
    void Fail(std::string_view key, std::string_view what) {
        if (!error_.empty()) return;
        error_ = name_ + ": ";
        for (size_t i = 0; i < path_.size(); ++i) {
            if (i > 0) error_ += '.';
            error_ += path_[i];
        }
        if (!key.empty()) {
            if (!path_.empty()) error_ += '.';
            error_ += key;
        }
        error_ += ": ";
        error_ += what;
    }

    /// The value of `key`, or nullptr when the key is absent or null.
    const Json* Optional(const Json& obj, const char* key) {
        if (!obj.is_object()) {
            Fail(key, "expected an object");
            return nullptr;
        }
        auto it = obj.find(key);
        if (it == obj.end() || it->is_null()) return nullptr;
        return &*it;
    }

    /// The value of `key`; an error when it is absent or null.
    const Json* Required(const Json& obj, const char* key) {
        const Json* v = Optional(obj, key);
        if (v == nullptr) Fail(key, "missing");
        return v;
    }

    bool AsString(const Json& v, std::string_view key, std::string& out) {
        if (!v.is_string()) return Fail(key, "expected a string"), false;
        out = v.get_ref<const std::string&>();
        return true;
    }

    bool AsInt(const Json& v, std::string_view key, int64_t& out) {
        if (v.is_number_integer() && !(v.is_number_unsigned() && v.get<uint64_t>() > uint64_t(kIntMax))) {
            out = v.get<int64_t>();
            return true;
        }
        return Fail(key, "expected an integer"), false;
    }

    /// A Float may be written as an integer token ("1" for 1.0).
    bool AsFloat(const Json& v, std::string_view key, double& out) {
        if (!v.is_number()) return Fail(key, "expected a number"), false;
        out = v.get<double>();
        return true;
    }

    bool AsBool(const Json& v, std::string_view key, bool& out) {
        if (!v.is_boolean()) return Fail(key, "expected true or false"), false;
        out = v.get<bool>();
        return true;
    }

    /// `unitMs` is the length of one wire unit: 1 for ms, 1000 for s, 60000 for m...
    bool AsDuration(const Json& v, std::string_view key, int64_t unitMs, std::chrono::milliseconds& out) {
        int64_t n = 0;
        if (!AsInt(v, key, n)) return false;
        out = std::chrono::milliseconds(n * unitMs);
        return true;
    }

    /// `parse` is a generated <Enum>FromWire or <Enum>FromCode function.
    template <class E, class W>
    bool AsEnum(const Json& v, std::string_view key, std::optional<E> (*parse)(W), E& out) {
        std::optional<E> e;
        if constexpr (std::is_same_v<W, std::string_view>) {
            if (v.is_string()) e = parse(std::string_view(v.get_ref<const std::string&>()));
        } else {
            int64_t n = 0;
            if (v.is_number_integer()) {
                n = v.get<int64_t>();
                if (n >= int64_t(std::numeric_limits<W>::min()) && n <= int64_t(std::numeric_limits<W>::max()))
                    e = parse(static_cast<W>(n));
            }
        }
        if (!e) return Fail(key, "unknown enum value"), false;
        out = *e;
        return true;
    }

    /// The array at `key` (or nullptr with an error).
    const Json* Array(const Json& obj, const char* key) {
        const Json* v = Required(obj, key);
        if (v != nullptr && !v->is_array()) return Fail(key, "expected an array"), nullptr;
        return v;
    }

    /// The object at `key` (or nullptr with an error).
    const Json* Object(const Json& obj, const char* key) {
        const Json* v = Required(obj, key);
        if (v != nullptr && !v->is_object()) return Fail(key, "expected an object"), nullptr;
        return v;
    }

    // Field shortcuts: Required + As*.
    bool String(const Json& obj, const char* key, std::string& out) {
        const Json* v = Required(obj, key);
        return v != nullptr && AsString(*v, key, out);
    }
    bool Int(const Json& obj, const char* key, int64_t& out) {
        const Json* v = Required(obj, key);
        return v != nullptr && AsInt(*v, key, out);
    }
    bool Float(const Json& obj, const char* key, double& out) {
        const Json* v = Required(obj, key);
        return v != nullptr && AsFloat(*v, key, out);
    }
    bool Bool(const Json& obj, const char* key, bool& out) {
        const Json* v = Required(obj, key);
        return v != nullptr && AsBool(*v, key, out);
    }
    bool Duration(const Json& obj, const char* key, int64_t unitMs, std::chrono::milliseconds& out) {
        const Json* v = Required(obj, key);
        return v != nullptr && AsDuration(*v, key, unitMs, out);
    }
    template <class E, class W>
    bool Enum(const Json& obj, const char* key, std::optional<E> (*parse)(W), E& out) {
        const Json* v = Required(obj, key);
        return v != nullptr && AsEnum(*v, key, parse, out);
    }

private:
    std::string name_;
    std::vector<std::string> path_;
    std::string error_;
};

}  // namespace json
}  // namespace rt_v1
}  // namespace canon

#endif  // CANON_RUNTIME_JSON_RT_V1
