// GENERATED by canon from pipeline/. DO NOT EDIT.
//
// Conformance vectors for every translated function of package pipeline. The
// expected results were computed by the Canon evaluator, which is the reference;
// this file checks that the C++ translation gives the same answers, errors included.
// Call RunPipelineConformance() from the runtime's test suite: it returns the
// number of failures and prints each one to stderr.
#include "pipeline.gen.h"

#include <cstdint>
#include <cstdio>
#include <string_view>

namespace sov::gen::conformance {

namespace {

std::string_view g_code;  // first evaluation error of the current call, empty if none

void Capture(std::string_view code, std::string_view /*message*/) {
    if (g_code.empty()) g_code = code;
}

struct PotionHealForVector {
    int64_t heal;
    int64_t missingHp;
    int64_t want;
    std::string_view code;  // expected error code; empty when `want` is expected
};

constexpr PotionHealForVector kPotionHealFor[] = {
    {500, 200, 200, ""},
    {500, 9000, 500, ""},
    {500, -5, 0, ""},
    {500, canon::kIntMin, 0, ""},
    {500, -1, 0, ""},
    {500, 0, 0, ""},
    {500, 1, 1, ""},
    {500, 499, 499, ""},
    {500, 500, 500, ""},
    {500, 501, 500, ""},
    {500, canon::kIntMax, 500, ""},
};

}  // namespace

int RunPipelineConformance() {
    int failures = 0;
    const canon::EvalErrorHandler previous = canon::SetEvalErrorHandler(&Capture);
    for (const PotionHealForVector& v : kPotionHealFor) {
        g_code = std::string_view();
        const int64_t got = detail::Potion_healFor(v.heal, v.missingHp);
        if (g_code != v.code || (v.code.empty() && got != v.want)) {
            std::fprintf(stderr,
                         "pipeline: Potion.healFor(heal=%lld, missingHp=%lld) = %lld [%.*s], canon says %lld [%.*s]\n",
                         static_cast<long long>(v.heal), static_cast<long long>(v.missingHp),
                         static_cast<long long>(got), static_cast<int>(g_code.size()), g_code.data(),
                         static_cast<long long>(v.want), static_cast<int>(v.code.size()), v.code.data());
            ++failures;
        }
    }
    canon::SetEvalErrorHandler(previous);
    return failures;
}

}  // namespace sov::gen::conformance
