package gorules

// svcWant is every finding the service fixture must produce, and nothing else.
var svcWant = []string{
	`bare-goroutine|internal/api/handlers.go|Used|func literal|0`,
	`bare-goroutine|internal/api/handlers.go|Used|worker|0`,
	`const-dup|internal/db/constants.go|const jsonType|application/json; charset=utf-8|0`,
	`const-dup|internal/db/constants.go|const kindUser|user|0`,
	`const-placement|internal/api/handlers.go|Helper|const localMax|1`,
	`const-placement|internal/api/handlers.go|const maxItems|const maxItems|1`,
	`const-placement|internal/api/handlers.go|var table|var table|2`,
	`const-placement|internal/api/roles.go|const Admin|const Admin|1`,
	`const-placement|internal/api/roles.go|const RoleMember|const RoleMember|1`,
	`const-placement|internal/db/queries.go|const insertUserQuery|const insertUserQuery|1`,
	`const-placement|internal/db/queries.go|const pickServer|const pickServer|1`,
	`env-key|internal/api/handlers.go|Server.ServeHTTP|Getenv config.EnvPort|0`,
	`env-key|internal/config/config.go|Port|Getenv SVC_DEBUG|0`,
	`err-inline|internal/api/handlers.go|Helper|inline|0`,
	`err-inline|internal/api/handlers.go|Helper|no wrap %d|0`,
	`err-placement|internal/api/handlers.go|var errMisplaced|errMisplaced|0`,
	`exported-but-local|internal/api/constants.go|MaxThing|const|0`,
	`exported-but-local|internal/api/constants.go|StatusPending|const|0`,
	`exported-but-local|internal/api/constants.go|StatusRunning|const|0`,
	`exported-but-local|internal/api/constants.go|TOTPEnabled|const|0`,
	`exported-but-local|internal/api/constants.go|TOTPState|type|0`,
	`exported-but-local|internal/api/errors.go|ErrSentinel|var|0`,
	`exported-but-local|internal/api/handlers.go|Dup|func|0`,
	`exported-but-local|internal/api/handlers.go|Helper|func|0`,
	`exported-but-local|internal/api/handlers.go|Hidden|type|0`,
	`exported-but-local|internal/api/handlers.go|Server.Internal|method|0`,
	`exported-but-local|internal/api/handlers.go|TestOnly|func|0`,
	`exported-but-local|internal/api/roles.go|Admin|const|0`,
	`exported-but-local|internal/api/roles.go|RoleMember|const|0`,
	`exported-but-local|internal/config/constants.go|MigrationFilePattern|const|0`,
	`exported-but-local|internal/db/constants.go|RoleAdmin|const|0`,
	`exported-but-local|internal/db/constants.go|StatusDone|const|0`,
	`exported-but-local|internal/db/constants.go|StatusPending|const|0`,
	`import-boundary|internal/api/handlers.go||example.com/svc/internal/db|0`,
	`import-boundary|internal/api/handlers.go||os/exec|0`,
	`log-direct|internal/api/handlers.go|Used|fmt.Println|0`,
	`log-direct|internal/api/handlers.go|Used|log.Printf|0`,
	`log-direct|internal/api/handlers.go|Used|println|0`,
	`magic-number|internal/api/handlers.go|Server.ServeHTTP|5|0`,
	`magic-number|internal/api/quiet.go|quiet|2|0`,
	`magic-number|internal/api/quiet.go|quiet|7|0`,
	`magic-string|internal/api||GET|2`,
	`magic-string|internal/api||^([0-9]{4})_([a-z0-9_]+)\.sql$|2`,
	`magic-string|internal/api||application/json|2`,
	`magic-string|internal/api||loud-value|2`,
	`magic-string|internal/api||only-here|2`,
	`magic-string|internal/db||application/json|1`,
	`reimplements-stdlib|internal/api/stdlib.go|containsString|contains|0`,
	`reimplements-stdlib|internal/api/stdlib.go|hasRune|contains|0`,
	`reimplements-stdlib|internal/api/stdlib.go|indexOf|index|0`,
	`reimplements-stdlib|internal/api/stdlib.go|keysOf|map keys m|0`,
	`reimplements-stdlib|internal/api/stdlib.go|maxOf|max|0`,
	`reimplements-stdlib|internal/api/stdlib.go|minInt|min|0`,
	`reimplements-stdlib|internal/api/stdlib.go|sortedKeys|map keys m|0`,
}

// libWant is every finding the library fixture must produce, and nothing else.
var libWant = []string{
	`bare-goroutine|geoip/geoip.go|Watch|Path|0`,
	`env-key|geoip/geoip.go|Path|Getenv envPath|0`,
	`exported-but-local|geoip/geoip.go|Path|func|0`,
	`exported-but-local|geoip/geoip.go|Watch|func|0`,
	`exported-but-local|middleware/constants.go|HeaderAuthorization|const|0`,
	`exported-but-local|middleware/constants.go|TOTPDisabled|const|0`,
	`exported-but-local|middleware/constants.go|TOTPEnabled|const|0`,
	`exported-but-local|middleware/constants.go|TOTPState|type|0`,
	`exported-but-local|migrate/constants.go|DefaultFilePattern|const|0`,
	`exported-but-local|roles/constants.go|RoleAdmin|const|0`,
	`exported-but-local|roles/constants.go|RoleMember|const|0`,
	`exported-but-local|safego/safego.go|SafeGo|func|0`,
	`magic-string|geoip||^([0-9]{4})_([a-z0-9_]+)\.sql$|2`,
}
