// Code generated by canon from pipeline/. DO NOT EDIT.

// Conformance vectors of package pipeline, computed by the Canon evaluator.

package potions

import (
	"math"
	"testing"

	"example.com/potions/rt"
)

// canonCatch runs f and returns its result, or the code of the *rt.EvalError it
// panicked with. Any other panic is re-raised.
func canonCatch[T any](f func() T) (got T, code string) {
	defer func() {
		if r := recover(); r != nil {
			e, ok := r.(*rt.EvalError)
			if !ok {
				panic(r)
			}
			code = e.Code
		}
	}()
	return f(), ""
}

func TestPotionHealForConformance(t *testing.T) {
	vectors := []struct {
		heal      int64
		missingHp int64
		want      int64
		code      string // expected error code; empty when want is expected
	}{
		{500, 200, 200, ""},
		{500, 9000, 500, ""},
		{500, -5, 0, ""},
		{500, math.MinInt64, 0, ""},
		{500, -1, 0, ""},
		{500, 0, 0, ""},
		{500, 1, 1, ""},
		{500, 499, 499, ""},
		{500, 500, 500, ""},
		{500, 501, 500, ""},
		{500, math.MaxInt64, 500, ""},
	}
	for _, v := range vectors {
		got, code := canonCatch(func() int64 { return potionHealFor(v.heal, v.missingHp) })
		if code != v.code || (v.code == "" && got != v.want) {
			t.Errorf("Potion.healFor(heal=%d, missingHp=%d) = %d [%s], canon says %d [%s]",
				v.heal, v.missingHp, got, code, v.want, v.code)
		}
	}
}
