// Code generated by canon from pipeline/. DO NOT EDIT.

// Package potions is generated by canon from package pipeline.
//
// A deliberately small object to show the whole pipeline, end to end.
// "Potion" is made up; the real item record has ~50 fields, but the pipeline is the same.
//
//	data/*.json      one file per potion, edited by hand or by the studio (like Items/**)
//	potion.canon     this file: the type, the rules, the view, what to emit
//	canon build      checks everything, then writes out/ (compare with expected/)
//
// Read-only by construction: fields are unexported, there are only getters, and
// only the generated loader fills values.
package potions

import (
	"encoding/json"
	"fmt"
	"iter"
	"path/filepath"
	"sync/atomic"
	"time"

	"example.com/potions/rt"
)

// PotionsSchema is the fingerprint of the schema of potions.json (types, wire names,
// units), not of its values. The loader refuses a file built from another schema.
const PotionsSchema = "pipeline.Potion@f750790e"

// Potion: A healing potion. Each one is a file under data/.
type Potion struct {
	id       string
	name     string
	heal     int64
	cooldown time.Duration
	stack    int64
	isStrong bool
}

// ID: The item define. Stored in inventories: never renamed.
func (self *Potion) ID() string { return self.id }

// Name: Text key of the displayed name.
func (self *Potion) Name() string { return self.name }

// Heal: Hit points restored.
func (self *Potion) Heal() int64 { return self.heal }

// Cooldown: Time before the same potion can be drunk again.
func (self *Potion) Cooldown() time.Duration { return self.cooldown }

// Stack: How many potions fit in one inventory slot.
func (self *Potion) Stack() int64 { return self.stack }

// IsStrong: No runtime input: computed by `canon build` for every potion and shipped as a value.
// The generated getter just returns it, in every language.
func (self *Potion) IsStrong() bool { return self.isStrong }

// HealFor: Needs a runtime input (the player's missing HP), so the body is translated into
// each target. Only the portable subset is allowed, and `canon build` emits a
// conformance test per target so the translations cannot drift.
func (self *Potion) HealFor(missingHp int64) int64 { return potionHealFor(self.heal, missingHp) }

// potionHealFor is translated from pipeline/potion.canon (Potion.healFor). The method
// and the conformance test both call it, so the test checks the code that runs.
func potionHealFor(heal int64, missingHp int64) int64 {
	return min(heal, max(missingHp, 0))
}

// Potions: One JSON file per potion, as today. Each file is one entry; findings point into it.
// Reloadable: tuned live during balance sessions, and runtimes keep potion ids, never
// Potion pointers, across ticks.
type Potions struct {
	rows rt.KeyedList[string, Potion]
}

// Len returns the number of entries.
func (self *Potions) Len() int { return self.rows.Len() }

// At returns entry i, in source order.
func (self *Potions) At(i int) *Potion { return self.rows.At(i) }

// All yields every entry in source order.
func (self *Potions) All() iter.Seq[*Potion] { return self.rows.All() }

// Find returns the entry whose id is key.
func (self *Potions) Find(key string) (*Potion, bool) { return self.rows.Find(key) }

// PipelineSnapshot holds every @reload value of package pipeline, loaded together and
// never modified. A reload builds a new snapshot; readers keep the one they hold.
type PipelineSnapshot struct {
	potions Potions
}

// Potions: One JSON file per potion, as today. Each file is one entry; findings point into it.
// Reloadable: tuned live during balance sessions, and runtimes keep potion ids, never
// Potion pointers, across ticks.
func (self *PipelineSnapshot) Potions() *Potions { return &self.potions }

// LoadPipelineSnapshot reads potions.json from dir. It fails if a file is missing, is
// not JSON, or was built from another schema. Values are not validated here: `canon
// build` already did, and filled every default.
func LoadPipelineSnapshot(dir string) (*PipelineSnapshot, error) {
	s := &PipelineSnapshot{}
	if err := loadPotions(filepath.Join(dir, "potions.json"), &s.potions); err != nil {
		return nil, err
	}
	return s, nil
}

// PipelineStore holds the current snapshot of package pipeline.
//
//	snap := potions.Store.Current()   // keep it for one tick or request
//	err := potions.Store.Reload(dir)  // the old snapshot lives while someone holds it
type PipelineStore struct {
	current atomic.Pointer[PipelineSnapshot]
}

// Current returns the current snapshot, or nil before the first successful Reload.
func (self *PipelineStore) Current() *PipelineSnapshot { return self.current.Load() }

// Reload loads a new snapshot from dir and swaps it in. On failure the current
// snapshot stays and the error is returned.
func (self *PipelineStore) Reload(dir string) error {
	s, err := LoadPipelineSnapshot(dir)
	if err != nil {
		return err
	}
	self.current.Store(s)
	return nil
}

// Store is the store of package pipeline.
var Store PipelineStore

type wirePotion struct {
	ID       *string `json:"dwID"`
	Name     *string `json:"szName"`
	Heal     *int64  `json:"nHeal"`
	Cooldown *int64  `json:"dwCooldownMs"`
	Stack    *int64  `json:"nStack"`
	IsStrong *bool   `json:"$isStrong"`
}

func decodePotion(name, path string, raw json.RawMessage, out *Potion) error {
	var w wirePotion
	if err := json.Unmarshal(raw, &w); err != nil {
		return fmt.Errorf("%s: %s: %w", name, path, err)
	}
	switch {
	case w.ID == nil:
		return rt.Missing(name, path, "dwID")
	case w.Name == nil:
		return rt.Missing(name, path, "szName")
	case w.Heal == nil:
		return rt.Missing(name, path, "nHeal")
	case w.Cooldown == nil:
		return rt.Missing(name, path, "dwCooldownMs")
	case w.Stack == nil:
		return rt.Missing(name, path, "nStack")
	case w.IsStrong == nil:
		return rt.Missing(name, path, "$isStrong")
	}
	*out = Potion{
		id:       *w.ID,
		name:     *w.Name,
		heal:     *w.Heal,
		cooldown: rt.DurationFromMs(*w.Cooldown),
		stack:    *w.Stack,
		isStrong: *w.IsStrong,
	}
	return nil
}

func loadPotions(path string, out *Potions) error {
	f, err := rt.ReadDataFile(path, PotionsSchema)
	if err != nil {
		return err
	}
	var rows []json.RawMessage
	if err := json.Unmarshal(f.Rows, &rows); err != nil {
		return fmt.Errorf("%s: rows: %w", path, err)
	}
	values := make([]Potion, len(rows))
	keys := make([]string, len(rows))
	for i, raw := range rows {
		if err := decodePotion(path, fmt.Sprintf("rows[%d].", i), raw, &values[i]); err != nil {
			return err
		}
		keys[i] = values[i].id
	}
	out.rows = rt.MakeKeyedList(values, keys)
	return nil
}
