// Code generated by canon from pipeline/. DO NOT EDIT.

// Package potions is generated by canon from package pipeline.
package potions

import (
	"encoding/json"
	"fmt"
	"iter"
	"slices"
	"strings"
	"sync/atomic"
	"time"

	"example.com/potions/rt"
)

// PotionsSchema is the fingerprint of the schema of potions.json (types, wire names,
// units), not of its values. The loader refuses a file built from another schema.
const PotionsSchema = "pipeline.Potion@f750790e"

// Potion: A healing potion. Each one is a file under data/.
type Potion struct {
	id       string
	name     string
	heal     int64
	cooldown time.Duration
	stack    int64
	isStrong bool
}

// ID: The item define. Stored in inventories: never renamed.
func (self *Potion) ID() string { return self.id }

// Name: Text key of the displayed name.
func (self *Potion) Name() string { return self.name }

// Heal: Hit points restored.
func (self *Potion) Heal() int64 { return self.heal }

// Cooldown: Time before the same potion can be drunk again.
func (self *Potion) Cooldown() time.Duration { return self.cooldown }

// Stack: How many potions fit in one inventory slot.
func (self *Potion) Stack() int64 { return self.stack }

// IsStrong: No runtime input: computed by `canon build` for every potion and shipped as a value.
// The generated getter just returns it, in every language.
func (self *Potion) IsStrong() bool { return self.isStrong }

// HealFor: Needs a runtime input (the player's missing HP), so the body is translated into
// each target. Only the portable subset is allowed, and `canon build` emits a
// conformance test per target so the translations cannot drift.
func (self *Potion) HealFor(missingHp int64) int64 { return potionHealFor(self.heal, missingHp) }

// potionHealFor is translated from pipeline/potion.canon (Potion.healFor). The method
// and the conformance test both call it, so the test checks the code that runs.
func potionHealFor(heal int64, missingHp int64) int64 {
	return min(heal, max(missingHp, 0))
}

// Potions: One JSON file per potion, as today. Each file is one entry; findings point into it.
// Reloadable: tuned live during balance sessions, and runtimes keep potion ids, never
// Potion pointers, across ticks.
type Potions struct {
	rows rt.KeyedList[string, Potion]
}

// Len returns the number of entries.
func (self *Potions) Len() int { return self.rows.Len() }

// At returns entry i, in source order.
func (self *Potions) At(i int) *Potion { return self.rows.At(i) }

// All yields every entry in source order.
func (self *Potions) All() iter.Seq[*Potion] { return self.rows.All() }

// Find returns the entry whose id is key.
func (self *Potions) Find(key string) (*Potion, bool) { return self.rows.Find(key) }

// PipelineSnapshot holds every @reload value of package pipeline, loaded together and
// never modified. A reload builds a new snapshot; readers keep the one they hold.
type PipelineSnapshot struct {
	potions Potions
}

// Potions: One JSON file per potion, as today. Each file is one entry; findings point into it.
// Reloadable: tuned live during balance sessions, and runtimes keep potion ids, never
// Potion pointers, across ticks.
func (self *PipelineSnapshot) Potions() *Potions { return &self.potions }

// LoadPipelineSnapshot reads potions.json from dir. It fails if a file is missing, is
// not JSON, or was built from another schema. Values are not validated here: `canon
// build` already did, and filled every default.
func LoadPipelineSnapshot(dir string) (*PipelineSnapshot, error) {
	s := &PipelineSnapshot{}
	if err := loadPotions(dir+"/potions.json", &s.potions); err != nil {
		return nil, err
	}
	return s, nil
}

// PipelineStore holds the current snapshot of package pipeline.
//
//	snap := potions.Store.Current()   // keep it for one tick or request
//	err := potions.Store.Reload(dir)  // the old snapshot lives while someone holds it
type PipelineStore struct {
	current atomic.Pointer[PipelineSnapshot]
}

// Current returns the current snapshot, or nil before the first successful Reload.
func (self *PipelineStore) Current() *PipelineSnapshot { return self.current.Load() }

// Reload loads a new snapshot from dir and swaps it in. On failure the current
// snapshot stays and the error is returned.
func (self *PipelineStore) Reload(dir string) error {
	s, err := LoadPipelineSnapshot(dir)
	if err != nil {
		return err
	}
	self.current.Store(s)
	return nil
}

// Store is the store of package pipeline.
var Store PipelineStore

// jsonObject reads the object at path: null or another kind fails the load.
func jsonObject(name, path string, raw json.RawMessage) (map[string]json.RawMessage, error) {
	if string(raw) == "null" {
		return nil, fmt.Errorf("%s: %s: null", name, strings.TrimSuffix(path, "."))
	}
	var obj map[string]json.RawMessage
	if json.Unmarshal(raw, &obj) != nil {
		return nil, fmt.Errorf("%s: %s: expected an object", name, strings.TrimSuffix(path, "."))
	}
	return obj, nil
}

// jsonKeys fails the load on a key of obj that is none of keys, sorted, but differs from one
// only in ASCII letter case: the smallest such key in byte order.
func jsonKeys(name, path string, obj map[string]json.RawMessage, keys ...string) error {
	bad, want := "", ""
	for k := range obj {
		if _, ok := slices.BinarySearch(keys, k); ok {
			continue
		}
		for _, key := range keys {
			if rt.EqualFold(k, key) && (want == "" || k < bad) {
				bad, want = k, key
			}
		}
	}
	if want == "" {
		return nil
	}
	return fmt.Errorf("%s: %s%s: differs from \"%s\" only in letter case", name, path, bad, want)
}

// jsonNeed is obj[key], which must be present and not null.
func jsonNeed(name, path string, obj map[string]json.RawMessage, key string) (json.RawMessage, error) {
	r, ok := obj[key]
	if !ok {
		return nil, rt.Missing(name, path, key)
	}
	if string(r) == "null" {
		return nil, fmt.Errorf("%s: %s%s: null", name, path, key)
	}
	return r, nil
}

// jsonMay is obj[key], nil when it is absent or null.
func jsonMay(obj map[string]json.RawMessage, key string) json.RawMessage {
	if r := obj[key]; string(r) != "null" {
		return r
	}
	return nil
}

// jsonCell is a lookup cell of obj: absent fails the load, null is none (nil).
func jsonCell(name, path string, obj map[string]json.RawMessage, key string) (json.RawMessage, error) {
	if _, ok := obj[key]; !ok {
		return nil, rt.Missing(name, path, key)
	}
	return jsonMay(obj, key), nil
}

// jsonRead reads raw into dst, a string, bool, float or array: null, or a value of another
// kind, fails the load at path+key, naming what was expected.
func jsonRead(name, path, key string, raw json.RawMessage, dst any) error {
	if string(raw) == "null" {
		return fmt.Errorf("%s: %s%s: null", name, path, key)
	}
	if json.Unmarshal(raw, dst) == nil {
		return nil
	}
	want := "expected a string"
	switch dst.(type) {
	case *bool:
		want = "expected true or false"
	case *float64:
		want = "expected a number"
	case *float32:
		want = "expected a number that fits Float32"
	case *[]json.RawMessage:
		want = "expected an array"
	}
	return fmt.Errorf("%s: %s%s: %s", name, path, key, want)
}

// jsonInt reads an integer token from lo to hi: null, or anything else, fails the load at
// path+key.
func jsonInt(name, path, key string, raw json.RawMessage, lo, hi int64) (int64, error) {
	if string(raw) == "null" {
		return 0, fmt.Errorf("%s: %s%s: null", name, path, key)
	}
	var n int64
	if json.Unmarshal(raw, &n) == nil && n >= lo && n <= hi {
		return n, nil
	}
	if lo == -1<<63 && hi == 1<<63-1 {
		return 0, fmt.Errorf("%s: %s%s: expected an integer", name, path, key)
	}
	return 0, fmt.Errorf("%s: %s%s: expected an integer from %d to %d", name, path, key, lo, hi)
}

// jsonSlot reads pairs slot k, v of obj: nil, nil for an empty slot, which sets *empty; an
// incomplete, null or late slot fails the load at its first key present.
func jsonSlot(name, path string, obj map[string]json.RawMessage, k, v string, empty *bool) (json.RawMessage, json.RawMessage, error) {
	kr, hasK := obj[k]
	vr, hasV := obj[v]
	first := k
	if !hasK {
		first = v
	}
	switch {
	case !hasK && !hasV:
		*empty = true
		return nil, nil, nil
	case hasK != hasV:
		return nil, nil, fmt.Errorf("%s: %s%s: incomplete pairs slot", name, path, first)
	case string(kr) == "null" || string(vr) == "null":
		return nil, nil, fmt.Errorf("%s: %s%s: null in a pairs slot", name, path, first)
	case *empty:
		return nil, nil, fmt.Errorf("%s: %s%s: pairs slot after an empty one", name, path, first)
	}
	return kr, vr, nil
}

// jsonSame reports raw JSON-equal to the none marker: a string after decoding, an integer
// only to an integer token, another number by value, [] and {} when empty.
func jsonSame(raw json.RawMessage, marker string) bool {
	switch marker[0] {
	case '"':
		var a, m string
		return json.Unmarshal(raw, &a) == nil && json.Unmarshal([]byte(marker), &m) == nil && a == m
	case '[':
		var a []json.RawMessage
		return json.Unmarshal(raw, &a) == nil && a != nil && len(a) == 0
	case '{':
		var a map[string]json.RawMessage
		return json.Unmarshal(raw, &a) == nil && a != nil && len(a) == 0
	case 't', 'f':
		return string(raw) == marker
	}
	var a, m int64
	if json.Unmarshal([]byte(marker), &m) == nil {
		return json.Unmarshal(raw, &a) == nil && a == m
	}
	var af, mf float64
	return json.Unmarshal(raw, &af) == nil && json.Unmarshal([]byte(marker), &mf) == nil && af == mf
}

func decodePotion(name, path string, raw json.RawMessage, out *Potion) error {
	obj, err := jsonObject(name, path, raw)
	if err != nil {
		return err
	}
	if err := jsonKeys(name, path, obj, "$isStrong", "dwCooldownMs", "dwID", "nHeal", "nStack", "szName"); err != nil {
		return err
	}
	r1, err := jsonNeed(name, path, obj, "dwID")
	if err != nil {
		return err
	}
	var v2 string
	if err := jsonRead(name, path, "dwID", r1, &v2); err != nil {
		return err
	}
	out.id = v2
	r3, err := jsonNeed(name, path, obj, "szName")
	if err != nil {
		return err
	}
	var v4 string
	if err := jsonRead(name, path, "szName", r3, &v4); err != nil {
		return err
	}
	out.name = v4
	r5, err := jsonNeed(name, path, obj, "nHeal")
	if err != nil {
		return err
	}
	n6, err := jsonInt(name, path, "nHeal", r5, -9223372036854775808, 9223372036854775807)
	if err != nil {
		return err
	}
	out.heal = n6
	r7, err := jsonNeed(name, path, obj, "dwCooldownMs")
	if err != nil {
		return err
	}
	n8, err := jsonInt(name, path, "dwCooldownMs", r7, -9223372036854, 9223372036854)
	if err != nil {
		return err
	}
	out.cooldown = rt.DurationFromMs(n8)
	r9, err := jsonNeed(name, path, obj, "nStack")
	if err != nil {
		return err
	}
	n10, err := jsonInt(name, path, "nStack", r9, -9223372036854775808, 9223372036854775807)
	if err != nil {
		return err
	}
	out.stack = n10
	r11, err := jsonNeed(name, path, obj, "$isStrong")
	if err != nil {
		return err
	}
	var v12 bool
	if err := jsonRead(name, path, "$isStrong", r11, &v12); err != nil {
		return err
	}
	out.isStrong = v12
	return nil
}

func loadPotions(path string, out *Potions) error {
	f, err := rt.ReadDataFile(path, PotionsSchema)
	if err != nil {
		return err
	}
	if f.Rows == nil {
		return rt.Missing(path, "", "rows")
	}
	var rows []json.RawMessage
	if err := jsonRead(path, "", "rows", f.Rows, &rows); err != nil {
		return err
	}
	values := make([]Potion, len(rows))
	keys := make([]string, len(rows))
	for i, raw := range rows {
		if err := decodePotion(path, fmt.Sprintf("rows[%d].", i), raw, &values[i]); err != nil {
			return err
		}
		keys[i] = values[i].id
	}
	out.rows = rt.MakeKeyedList(values, keys)
	return nil
}
