// Code generated by canon: Go runtime rt v1. DO NOT EDIT.

// Package rt is the runtime of the Go code canon generates.
package rt

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"iter"
	"math"
	"os"
	"strconv"
	"strings"
	"time"
	"unicode/utf8"
)

// Version is the version of this runtime. Generated code of one output directory
// always uses the rt package written next to it.
const Version = 1

// ---------------------------------------------------------------------------
// Read-only collections
// ---------------------------------------------------------------------------

// List is a read-only list. The zero value is an empty list.
type List[T any] struct{ s []T }

// MakeList is for generated code. The list keeps s: the caller must not modify it.
func MakeList[T any](s []T) List[T] { return List[T]{s: s} }

// Len returns the number of elements.
func (l List[T]) Len() int { return len(l.s) }

// At returns element i. It panics if i is out of range, like a slice.
func (l List[T]) At(i int) T { return l.s[i] }

// All yields the elements in order.
func (l List[T]) All() iter.Seq[T] {
	return func(yield func(T) bool) {
		for _, v := range l.s {
			if !yield(v) {
				return
			}
		}
	}
}

// Clone returns a new slice holding the elements, which the caller may modify.
func (l List[T]) Clone() []T { return append([]T(nil), l.s...) }

// Map is a read-only map that iterates in source order. The zero value is empty.
type Map[K comparable, V any] struct {
	keys  []K
	vals  []V
	index map[K]int
}

// MakeMap is for generated code: keys are unique, vals[i] belongs to keys[i]. The map
// keeps both slices: the caller must not modify them.
func MakeMap[K comparable, V any](keys []K, vals []V) Map[K, V] {
	index := make(map[K]int, len(keys))
	for i, k := range keys {
		index[k] = i
	}
	return Map[K, V]{keys: keys, vals: vals, index: index}
}

// Len returns the number of entries.
func (m Map[K, V]) Len() int { return len(m.keys) }

// Get returns the value of k, and whether k is present.
func (m Map[K, V]) Get(k K) (V, bool) {
	i, ok := m.index[k]
	if !ok {
		var zero V
		return zero, false
	}
	return m.vals[i], true
}

// All yields the entries in source order.
func (m Map[K, V]) All() iter.Seq2[K, V] {
	return func(yield func(K, V) bool) {
		for i, k := range m.keys {
			if !yield(k, m.vals[i]) {
				return
			}
		}
	}
}

// KeyedList is a read-only list of records that are unique by a key.
type KeyedList[K comparable, T any] struct {
	rows  []T
	index map[K]int
}

// MakeKeyedList is for generated code: keys[i] is the key of rows[i], keys are unique.
// The list keeps rows: the caller must not modify it.
func MakeKeyedList[K comparable, T any](rows []T, keys []K) KeyedList[K, T] {
	index := make(map[K]int, len(keys))
	for i, k := range keys {
		index[k] = i
	}
	return KeyedList[K, T]{rows: rows, index: index}
}

// Len returns the number of rows.
func (l KeyedList[K, T]) Len() int { return len(l.rows) }

// At returns row i. It panics if i is out of range, like a slice.
func (l KeyedList[K, T]) At(i int) *T { return &l.rows[i] }

// All yields every row in source order.
func (l KeyedList[K, T]) All() iter.Seq[*T] {
	return func(yield func(*T) bool) {
		for i := range l.rows {
			if !yield(&l.rows[i]) {
				return
			}
		}
	}
}

// Find returns the row whose key is k.
func (l KeyedList[K, T]) Find(k K) (*T, bool) {
	i, ok := l.index[k]
	if !ok {
		return nil, false
	}
	return &l.rows[i], true
}

// ---------------------------------------------------------------------------
// Evaluation errors (DECISIONS 19): translated code panics with *EvalError.
// ---------------------------------------------------------------------------

// EvalError is an error the Canon evaluator would also report, with its code.
type EvalError struct {
	Code    string // Canon diagnostic code, e.g. "E4101"
	Message string
}

func (e *EvalError) Error() string { return e.Code + ": " + e.Message }

// Fail panics with an *EvalError.
func Fail(code, message string) { panic(&EvalError{Code: code, Message: message}) }

// ---------------------------------------------------------------------------
// Checked arithmetic (CONFORMANCE.md §3). Int is int64, Float is float64,
// Duration is int64 milliseconds.
// ---------------------------------------------------------------------------

func AddInt(a, b int64) int64 {
	if (b > 0 && a > math.MaxInt64-b) || (b < 0 && a < math.MinInt64-b) {
		Fail("E4101", "integer overflow in +")
	}
	return a + b
}

func SubInt(a, b int64) int64 {
	if (b < 0 && a > math.MaxInt64+b) || (b > 0 && a < math.MinInt64+b) {
		Fail("E4101", "integer overflow in -")
	}
	return a - b
}

func MulInt(a, b int64) int64 {
	var overflow bool
	if a > 0 {
		if b > 0 {
			overflow = a > math.MaxInt64/b
		} else {
			overflow = b < math.MinInt64/a
		}
	} else if b > 0 {
		overflow = a < math.MinInt64/b
	} else {
		overflow = a != 0 && b < math.MaxInt64/a
	}
	if overflow {
		Fail("E4101", "integer overflow in *")
	}
	return a * b
}

func DivInt(a, b int64) int64 {
	if b == 0 {
		Fail("E4102", "integer division by zero")
	}
	if a == math.MinInt64 && b == -1 {
		Fail("E4101", "integer overflow in /")
	}
	return a / b
}

func ModInt(a, b int64) int64 {
	if b == 0 {
		Fail("E4102", "integer division by zero in %")
	}
	if b == -1 {
		return 0
	}
	return a % b
}

func NegInt(a int64) int64 {
	if a == math.MinInt64 {
		Fail("E4101", "integer overflow in unary -")
	}
	return -a
}

func AbsInt(a int64) int64 {
	if a == math.MinInt64 {
		Fail("E4101", "integer overflow in abs")
	}
	if a < 0 {
		return -a
	}
	return a
}

func ClampInt(x, lo, hi int64) int64 {
	if lo > hi {
		Fail("E4108", "clamp with lo > hi")
	}
	return min(max(x, lo), hi)
}

// CheckFloat: any Float operation whose result is NaN or infinite is E4104.
func CheckFloat(x float64) float64 {
	if math.IsNaN(x) || math.IsInf(x, 0) {
		Fail("E4104", "float result is not finite")
	}
	return x
}

func AddFloat(a, b float64) float64 { return CheckFloat(a + b) }
func SubFloat(a, b float64) float64 { return CheckFloat(a - b) }
func MulFloat(a, b float64) float64 { return CheckFloat(a * b) }
func DivFloat(a, b float64) float64 { return CheckFloat(a / b) }
func ModFloat(a, b float64) float64 { return CheckFloat(math.Mod(a, b)) }
func NegFloat(a float64) float64    { return -a }
func AbsFloat(a float64) float64    { return math.Abs(a) }

// MinFloat and MaxFloat order -0.0 before +0.0 (IEEE 754-2019 minimum and maximum).
func MinFloat(a, b float64) float64 {
	if a < b {
		return a
	}
	if b < a {
		return b
	}
	if math.Signbit(a) {
		return a
	}
	return b
}

func MaxFloat(a, b float64) float64 {
	if a > b {
		return a
	}
	if b > a {
		return b
	}
	if math.Signbit(a) {
		return b
	}
	return a
}

func ClampFloat(x, lo, hi float64) float64 {
	if lo > hi {
		Fail("E4108", "clamp with lo > hi")
	}
	return MinFloat(MaxFloat(x, lo), hi)
}

func IntToFloat(i int64) float64 { return float64(i) }

// FloatToInt is Int(f): it truncates toward zero; E4103 when the result does not fit.
func FloatToInt(f float64) int64 {
	if !(f >= -9223372036854775808.0 && f < 9223372036854775808.0) {
		Fail("E4103", "float out of the Int range")
	}
	return int64(f)
}

func FloorFloat(f float64) int64 { return FloatToInt(math.Floor(f)) }
func CeilFloat(f float64) int64  { return FloatToInt(math.Ceil(f)) }

// RoundFloat rounds half away from zero.
func RoundFloat(f float64) int64 { return FloatToInt(math.Round(f)) }

// DivDuration is Duration / Duration, a Float; a zero divisor is E4102.
func DivDuration(a, b int64) float64 {
	if b == 0 {
		Fail("E4102", "duration division by zero")
	}
	return CheckFloat(float64(a) / float64(b))
}

// CheckIntRange checks the range refinement of a parameter or a return value: E3204.
func CheckIntRange(v, lo, hi int64) int64 {
	if v < lo || v > hi {
		Fail("E3204", "value outside its refinement range")
	}
	return v
}

func CheckFloatRange(v, lo, hi float64) float64 {
	if v < lo || v > hi {
		Fail("E3204", "value outside its refinement range")
	}
	return v
}

// CheckIntWidth checks the range of a sized integer type (Int8 ... UInt64): E3201.
func CheckIntWidth(v, lo, hi int64) int64 {
	if v < lo || v > hi {
		Fail("E3201", "value does not fit its sized integer type")
	}
	return v
}

// ToFloat32 stores a Float into a Float32, rounding to nearest-even; overflow is E3202.
func ToFloat32(v float64) float32 {
	if math.Abs(v) >= 3.4028235677973366e+38 {
		Fail("E3202", "value overflows Float32")
	}
	return float32(v)
}

// CheckFloatArg: a Float argument that is NaN or infinite is E4104 on entry.
func CheckFloatArg(v float64) float64 { return CheckFloat(v) }

// DurationToMs converts a runtime argument to Canon's millisecond count; any
// sub-millisecond part is truncated toward zero.
func DurationToMs(d time.Duration) int64 { return d.Milliseconds() }

// DurationFromMs converts a Canon duration to a time.Duration.
func DurationFromMs(ms int64) time.Duration { return time.Duration(ms) * time.Millisecond }

// ---------------------------------------------------------------------------
// Data files
// ---------------------------------------------------------------------------

// DataFile is the envelope of a data file written by `canon build`.
type DataFile struct {
	Schema string          `json:"$schema"`
	Rows   json.RawMessage `json:"rows"`
	Value  json.RawMessage `json:"value"`
}

// ReadDataFile reads a data file and checks its $schema against schema.
func ReadDataFile(path, schema string) (*DataFile, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	return ParseDataFile(path, raw, schema)
}

// ParseDataFile parses a data file (name is used in messages) and checks its $schema. Keys
// match exactly, and no object of the file may hold a key twice.
func ParseDataFile(name string, raw []byte, schema string) (*DataFile, error) {
	raw = bytes.TrimPrefix(raw, []byte("\xef\xbb\xbf"))
	if err := checkObjects(name, raw); err != nil {
		return nil, err
	}
	var top map[string]json.RawMessage
	if json.Unmarshal(raw, &top) != nil {
		return nil, notData(name)
	}
	if err := checkEnvelope(name, top); err != nil {
		return nil, err
	}
	f := DataFile{Rows: top["rows"], Value: top["value"]}
	got := "<none>"
	if json.Unmarshal(top["$schema"], &f.Schema) == nil && bytes.HasPrefix(top["$schema"], []byte(`"`)) {
		got = f.Schema
	}
	if got != schema {
		return nil, fmt.Errorf("%s: built from schema %s, this binary expects %s. Rebuild the data or deploy the matching binary", name, got, schema)
	}
	return &f, nil
}

// notData is the error of a file that is not one valid JSON object.
func notData(name string) error { return fmt.Errorf("%s: not a canon data file (invalid JSON)", name) }

// EqualFold reports whether a and b are equal ignoring the case of ASCII letters, and only of
// them. A generated loader refuses a key that matches an expected one only this way.
func EqualFold(a, b string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := 0; i < len(a); i++ {
		if lowerASCII(a[i]) != lowerASCII(b[i]) {
			return false
		}
	}
	return true
}

func lowerASCII(c byte) byte {
	if 'A' <= c && c <= 'Z' {
		return c + 'a' - 'A'
	}
	return c
}

// envelopeKeys are the keys of a data file's top-level object.
var envelopeKeys = []string{"$fns", "$schema", "rows", "value"}

// checkEnvelope refuses a top-level key equal to an envelope key only ignoring letter case,
// naming the smallest such key in byte order.
func checkEnvelope(name string, top map[string]json.RawMessage) error {
	bad, want := "", ""
	for key := range top {
		for _, k := range envelopeKeys {
			if key != k && EqualFold(key, k) && (want == "" || key < bad) {
				bad, want = key, k
			}
		}
	}
	if want != "" {
		return fmt.Errorf("%s: %s: differs from \"%s\" only in letter case", name, bad, want)
	}
	return nil
}

// maxNesting is the deepest nesting of arrays and objects a data file may hold (WIRE.md §3.1).
const maxNesting = 512

// checkObjects reads the file once, in order: it must be one JSON object of valid UTF-8, with
// no escaped unpaired surrogate and no number beyond float64; no object in it may hold a key
// twice, and nothing may nest deeper than maxNesting. The first finding is the error.
func checkObjects(name string, raw []byte) error {
	type frame struct {
		keys map[string]bool // the keys seen so far; nil in an array
		path string          // the container's path
		next int             // an array's next index
	}
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.UseNumber()
	next := func() (json.Token, bool) {
		start := dec.InputOffset()
		tok, err := dec.Token()
		if err != nil || !validSpan(raw[start:dec.InputOffset()]) {
			return nil, false
		}
		if n, isNumber := tok.(json.Number); isNumber {
			if _, err := strconv.ParseFloat(string(n), 64); err != nil {
				return nil, false
			}
		}
		return tok, true
	}
	if tok, ok := next(); !ok || tok != json.Delim('{') {
		return notData(name)
	}
	stack := []*frame{{keys: map[string]bool{}}}
	for len(stack) > 0 {
		tok, ok := next()
		if !ok {
			return notData(name)
		}
		top := stack[len(stack)-1]
		if tok == json.Delim('}') || tok == json.Delim(']') {
			stack = stack[:len(stack)-1]
			continue
		}
		var at string
		if top.keys != nil {
			key, _ := tok.(string)
			at = key
			if top.path != "" {
				at = top.path + "." + key
			}
			if top.keys[key] {
				return fmt.Errorf("%s: %s: duplicate key", name, at)
			}
			top.keys[key] = true
			if tok, ok = next(); !ok {
				return notData(name)
			}
		} else {
			at = top.path + "[" + strconv.Itoa(top.next) + "]"
			top.next++
		}
		if (tok == json.Delim('{') || tok == json.Delim('[')) && len(stack) >= maxNesting {
			return fmt.Errorf("%s: %s: nested deeper than %d levels", name, at, maxNesting)
		}
		switch tok {
		case json.Delim('{'):
			stack = append(stack, &frame{keys: map[string]bool{}, path: at})
		case json.Delim('['):
			stack = append(stack, &frame{path: at})
		}
	}
	if _, err := dec.Token(); !errors.Is(err, io.EOF) {
		return notData(name)
	}
	return nil
}

// validSpan reports bytes of the file that are UTF-8 and escape no unpaired UTF-16 surrogate,
// which encoding/json would read as U+FFFD.
func validSpan(b []byte) bool {
	if !utf8.Valid(b) {
		return false
	}
	for i := 0; i+1 < len(b); i++ {
		if b[i] != '\\' {
			continue
		}
		i++
		if b[i] != 'u' || i+4 >= len(b) {
			continue
		}
		r, _ := strconv.ParseUint(string(b[i+1:i+5]), 16, 32)
		switch {
		case r >= 0xdc00 && r <= 0xdfff:
			return false
		case r >= 0xd800 && r <= 0xdbff:
			low := uint64(0)
			if i+10 < len(b) && b[i+5] == '\\' && b[i+6] == 'u' {
				low, _ = strconv.ParseUint(string(b[i+7:i+11]), 16, 32)
			}
			if low < 0xdc00 || low > 0xdfff {
				return false
			}
			i += 10
		default:
			i += 4
		}
	}
	return true
}

// Missing is the error of a required key absent from a data file.
func Missing(name, path, key string) error {
	return fmt.Errorf("%s: %s%s: missing", name, path, key)
}

// ---------------------------------------------------------------------------
// Runtime inputs (EVALUATION.md §11.3): environment text is read as the literal of
// the field's type.
// ---------------------------------------------------------------------------

// Env returns the variable's value. An unset or empty variable is unset.
func Env(name string) (string, bool) {
	v, ok := os.LookupEnv(name)
	return v, ok && v != ""
}

func isDec(c byte) bool { return c >= '0' && c <= '9' }

// allDigits reports whether s is one or more decimal digits.
func allDigits(s string) bool {
	if s == "" {
		return false
	}
	for i := 0; i < len(s); i++ {
		if !isDec(s[i]) {
			return false
		}
	}
	return true
}

// digits removes the '_' separators of a Canon decimal literal (duration parts).
func digits(s string) (string, bool) {
	if s == "" || !isDec(s[0]) || !isDec(s[len(s)-1]) {
		return "", false
	}
	var b strings.Builder
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case isDec(c):
			b.WriteByte(c)
		case c == '_' && isDec(s[i+1]):
		default:
			return "", false
		}
	}
	return b.String(), true
}

// ParseIntLiteral reads an integer input: decimal digits with an optional leading '-',
// no separator and no prefix.
func ParseIntLiteral(s string) (int64, error) {
	if !allDigits(strings.TrimPrefix(s, "-")) {
		return 0, fmt.Errorf("%q is not an integer", s)
	}
	n, err := strconv.ParseInt(s, 10, 64)
	if err != nil {
		return 0, fmt.Errorf("%q is out of the Int range", s)
	}
	return n, nil
}

// ParseFloatLiteral reads a Float input: -?[0-9]+(\.[0-9]+)?([eE][+-]?[0-9]+)?, finite.
func ParseFloatLiteral(s string) (float64, error) {
	bad := fmt.Errorf("%q is not a number", s)
	body := strings.TrimPrefix(s, "-")
	mant, exp, hasExp := strings.Cut(body, "e")
	if !hasExp {
		mant, exp, hasExp = strings.Cut(body, "E")
	}
	intPart, frac, hasFrac := strings.Cut(mant, ".")
	if !allDigits(intPart) || (hasFrac && !allDigits(frac)) {
		return 0, bad
	}
	if hasExp {
		if exp != "" && (exp[0] == '+' || exp[0] == '-') {
			exp = exp[1:]
		}
		if !allDigits(exp) {
			return 0, bad
		}
	}
	f, err := strconv.ParseFloat(s, 64)
	if err != nil || math.IsInf(f, 0) {
		return 0, fmt.Errorf("%q is out of the Float range", s)
	}
	return f, nil
}

// ParseStringLiteral reads a String input: the text byte for byte, which must be UTF-8.
func ParseStringLiteral(s string) (string, error) {
	if !utf8.ValidString(s) {
		return "", fmt.Errorf("%q is not valid UTF-8", s)
	}
	return s, nil
}

// ParseBoolLiteral reads true or false.
func ParseBoolLiteral(s string) (bool, error) {
	switch s {
	case "true":
		return true, nil
	case "false":
		return false, nil
	}
	return false, fmt.Errorf("%q is not true or false", s)
}

// ParseDurationLiteral reads a Canon duration literal: 250ms, 90s, 1h30m, -5m.
// Units d h m s ms appear at most once each, largest first.
func ParseDurationLiteral(s string) (time.Duration, error) {
	bad := fmt.Errorf("%q is not a duration", s)
	body := strings.TrimPrefix(s, "-")
	units := []struct {
		suffix string
		ms     int64
	}{{"d", 86_400_000}, {"h", 3_600_000}, {"ms", 1}, {"m", 60_000}, {"s", 1_000}}
	order := map[string]int{"d": 0, "h": 1, "m": 2, "s": 3, "ms": 4}
	var total int64
	last := -1
	for body != "" {
		i := 0
		for i < len(body) && (isDec(body[i]) || body[i] == '_') {
			i++
		}
		d, ok := digits(body[:i])
		if !ok {
			return 0, bad
		}
		rest := body[i:]
		matched := false
		for _, u := range units {
			if !strings.HasPrefix(rest, u.suffix) {
				continue
			}
			if order[u.suffix] <= last {
				return 0, bad
			}
			last = order[u.suffix]
			n, err := strconv.ParseInt(d, 10, 64)
			if err != nil || n > (math.MaxInt64-total)/u.ms {
				return 0, fmt.Errorf("%q is out of the Duration range", s)
			}
			total += n * u.ms
			body = rest[len(u.suffix):]
			matched = true
			break
		}
		if !matched {
			return 0, bad
		}
	}
	if last < 0 {
		return 0, bad
	}
	if total > math.MaxInt64/int64(time.Millisecond) {
		return 0, fmt.Errorf("%q is out of the Duration range", s)
	}
	if strings.HasPrefix(s, "-") {
		total = -total
	}
	return DurationFromMs(total), nil
}

// InputError is the error of a runtime input that is missing or invalid.
func InputError(name, reason string) error {
	return fmt.Errorf("environment variable %s: %s", name, reason)
}
