// GENERATED by canon from teamboard/. DO NOT EDIT.
import type { Role } from "../roles.generated.js";
import { RoleIndex } from "../roles.generated.js";
import type { Icon, Tone } from "../ui.generated.js";

// ---------------------------------------------------------------------------
// canon runtime, TypeScript v1 (CODEGEN.md §8.2). Identical in every generated file.
// ---------------------------------------------------------------------------

/** An error the Canon evaluator would also report, with its code ("E4101"). */
export class CanonEvalError extends Error {
  readonly code: string;
  constructor(code: string, message: string) {
    super(code + ": " + message);
    this.name = "CanonEvalError";
    this.code = code;
  }
}

/** A table or keyed list: entries in source order, lookup by key. */
export interface CanonTable<K, T> {
  readonly length: number;
  readonly all: ReadonlyArray<T>;
  at(i: number): T;
  find(key: K): T | null;
}

function canonTable<K, T>(rows: ReadonlyArray<T>, keyOf: (row: T) => K): CanonTable<K, T> {
  const index = new Map<K, number>();
  rows.forEach((row, i) => index.set(keyOf(row), i));
  return Object.freeze({
    length: rows.length,
    all: rows,
    at: (i: number): T => rows[i],
    find: (key: K): T | null => {
      const i = index.get(key);
      return i === undefined ? null : rows[i];
    },
  });
}

/** Deep-freezes plain objects and arrays (CanonMaps are already read-only). */
function canonFreeze<T>(x: T): T {
  if (typeof x === "object" && x !== null && !Object.isFrozen(x)) {
    Object.freeze(x);
    for (const v of Object.values(x)) canonFreeze(v);
  }
  return x;
}
// ---------------------------------------------------------------------------

/** Format version of the taxonomy (taxonomy.json's `version`). */
export const VERSION = 7;

/** Who may set a flag or make a transition. */
export type Actor = "reporter" | "triager" | "reporter_or_triager";
export const ActorMembers: ReadonlyArray<Actor> = Object.freeze(["reporter", "triager", "reporter_or_triager"]);
export const ActorNames: Readonly<Record<Actor, string>> = Object.freeze({ reporter: "reporter", triager: "triager", reporter_or_triager: "reporter_or_triager" });
export const ActorIndex: Readonly<Record<Actor, number>> = Object.freeze({ reporter: 0, triager: 1, reporter_or_triager: 2 });

/** Inputs a status transition may collect. */
export type PostField = "assignee" | "fixed_in" | "reason" | "duplicate_of";
export const PostFieldMembers: ReadonlyArray<PostField> = Object.freeze(["assignee", "fixed_in", "reason", "duplicate_of"]);
export const PostFieldNames: Readonly<Record<PostField, string>> = Object.freeze({ assignee: "assignee", fixed_in: "fixed_in", reason: "reason", duplicate_of: "duplicate_of" });
export const PostFieldIndex: Readonly<Record<PostField, number>> = Object.freeze({ assignee: 0, fixed_in: 1, reason: 2, duplicate_of: 3 });

export type IntentId = "issue" | "idea";
export const IntentIdIndex: Readonly<Record<IntentId, number>> = Object.freeze({ issue: 0, idea: 1 });

export type FlagId = "blocking" | "sensitive";
export const FlagIdIndex: Readonly<Record<FlagId, number>> = Object.freeze({ blocking: 0, sensitive: 1 });

export type StatusId = "open" | "taken" | "fixed" | "verified" | "wont_do" | "duplicate";
export const StatusIdIndex: Readonly<Record<StatusId, number>> = Object.freeze({ open: 0, taken: 1, fixed: 2, verified: 3, wont_do: 4, duplicate: 5 });

export type ColumnId = "unclaimed" | "taken" | "fixed" | "done";
export const ColumnIdIndex: Readonly<Record<ColumnId, number>> = Object.freeze({ unclaimed: 0, taken: 1, fixed: 2, done: 3 });

export type SeverityId = "low" | "normal" | "critical";
export const SeverityIdIndex: Readonly<Record<SeverityId, number>> = Object.freeze({ low: 0, normal: 1, critical: 2 });

export type AreaGroupId = "in_game" | "out_game" | "internal";
export const AreaGroupIdIndex: Readonly<Record<AreaGroupId, number>> = Object.freeze({ in_game: 0, out_game: 1, internal: 2 });

export type AreaId = "game" | "balance" | "website" | "resource_studio" | "game_server" | "client" | "resource" | "sovcommon" | "admin_panel" | "analytics" | "team_board" | "internal";
export const AreaIdIndex: Readonly<Record<AreaId, number>> = Object.freeze({ game: 0, balance: 1, website: 2, resource_studio: 3, game_server: 4, client: 5, resource: 6, sovcommon: 7, admin_panel: 8, analytics: 9, team_board: 10, internal: 11 });

/** What kind of post this is; `minRole` gates who may post it. */
export interface Intent {
  readonly id: IntentId;
  readonly retired: boolean;
  /** Colour of the intent's badge. */
  readonly tone: Tone;
  /** Icon of the intent's badge. */
  readonly icon: Icon;
  /** What the reporter picks, as a sentence. */
  readonly label: string;
  /** The lowest role that may post with this intent. */
  readonly minRole: Role;
}

/** One of the reporter's booleans. */
export interface Flag {
  readonly id: FlagId;
  readonly retired: boolean;
  /** Colour of the flag's badge. */
  readonly tone: Tone;
  /** Icon of the flag's badge. */
  readonly icon: Icon;
  /** What the reporter ticks, as a sentence. */
  readonly label: string;
  /** Shown under the label. */
  readonly hint: string | null;
  /** Who may set the flag. */
  readonly setBy: Actor;
  /** Who may see that the flag was set; `none` means whoever can see the post. */
  readonly viewMinRole: Role | null;
}

/** One point of the post lifecycle. */
export interface Status {
  readonly id: StatusId;
  readonly retired: boolean;
  /** Colour of the status badge. */
  readonly tone: Tone;
  /** Name of the status. */
  readonly label: string;
  /** A terminal status closes the post. It can still be reopened through `next`. */
  readonly terminal: boolean;
  /** The closed set of statuses a post may move to from here. */
  readonly next: ReadonlyArray<StatusId>;
  /** Inputs a transition INTO this status must collect. */
  readonly requires: ReadonlyArray<PostField>;
  /** Inputs a transition INTO this status may collect. */
  readonly optional: ReadonlyArray<PostField>;
  /** Who, besides a triager, may make the transition into this status. */
  readonly by: Actor | null;
}

/** Set by a triager only. The reporter's single signal is the `blocking` flag. */
export interface Severity {
  readonly id: SeverityId;
  readonly retired: boolean;
  /** Colour of the severity badge. */
  readonly tone: Tone;
  /** Name of the severity. */
  readonly label: string;
  /** The severity a triaged post gets unless the triager picks another. */
  readonly default: boolean;
}

/** A header the area picker and the move-to-area menu group areas under. */
export interface AreaGroup {
  readonly id: AreaGroupId;
  readonly retired: boolean;
  /** Header text. */
  readonly label: string;
}

/** Where the reporter stood, never which component is at fault. */
export interface Area {
  readonly id: AreaId;
  readonly retired: boolean;
  /** The header the area is listed under. */
  readonly group: AreaGroupId;
  /** Family: series_1 game, series_2 web, series_3 tooling, series_4 internal. */
  readonly tone: Tone;
  /** Icon next to the area's name. */
  readonly icon: Icon;
  /** Name of the area. */
  readonly label: string;
  /** Shown under the label. */
  readonly hint: string | null;
  /** Gates posting AND viewing. */
  readonly minRole: Role;
  /** Technical areas a triager typically moves a post into. Orders the move menu only. */
  readonly routesTo: ReadonlyArray<AreaId>;
}

/** One fixed column of the deck: a named set of statuses. */
export interface Column {
  readonly id: ColumnId;
  readonly retired: boolean;
  /** Column header. */
  readonly label: string;
  /** Icon in the column header. */
  readonly icon: Icon;
  /** The statuses whose posts the column shows. */
  readonly statuses: ReadonlyArray<StatusId>;
  /** Adds a multi-select of eligible members inside the column. */
  readonly assigneeFilter: boolean;
  /** Lets a viewer collapse the column to the rail (capped by `deck.maxHidden`). */
  readonly hideable: boolean;
}

/** The deck: fixed columns, in order. Nobody adds, removes or edits a column. */
export interface Deck {
  /** The only arrangements: all in one row, or a 2x2 grid. */
  readonly layouts: ReadonlyArray<string>;
  /** How many columns may be collapsed at once, so the deck never goes fully empty. */
  readonly maxHidden: number;
}

/** One group header with the areas shown under it. */
export interface AreaSection {
  /** The header. */
  readonly group: AreaGroupId;
  /** The areas under it, in declaration order. */
  readonly areas: ReadonlyArray<AreaId>;
}

/** What a post can be. */
export const intents: CanonTable<IntentId, Intent> = canonTable(canonFreeze<ReadonlyArray<Intent>>([
  { id: "issue", retired: false, tone: "warning", icon: "alert-triangle", label: "Something is wrong", minRole: "gm_junior" },
  { id: "idea", retired: false, tone: "accent", icon: "lightbulb", label: "Idea or request", minRole: "gm_junior" },
]), (e) => e.id);

/** The reporter's booleans. */
export const flags: CanonTable<FlagId, Flag> = canonTable(canonFreeze<ReadonlyArray<Flag>>([
  { id: "blocking", retired: false, tone: "danger", icon: "hand", label: "This blocks my work", hint: null, setBy: "reporter", viewMinRole: null },
  { id: "sensitive", retired: false, tone: "warning", icon: "lock", label: "Only the dev team should see", hint: "Exploits, dupes, security problems.", setBy: "reporter", viewMinRole: "maintainer" },
]), (e) => e.id);

/** The post lifecycle. */
export const statuses: CanonTable<StatusId, Status> = canonTable(canonFreeze<ReadonlyArray<Status>>([
  { id: "open", retired: false, tone: "warning", label: "Open", terminal: false, next: ["taken", "wont_do", "duplicate"], requires: [], optional: [], by: null },
  { id: "taken", retired: false, tone: "info", label: "Taken", terminal: false, next: ["open", "fixed", "wont_do", "duplicate"], requires: ["assignee"], optional: [], by: null },
  { id: "fixed", retired: false, tone: "accent", label: "Fixed", terminal: false, next: ["verified", "open"], requires: [], optional: ["fixed_in"], by: null },
  { id: "verified", retired: false, tone: "success", label: "Verified", terminal: true, next: ["open"], requires: [], optional: [], by: "reporter_or_triager" },
  { id: "wont_do", retired: false, tone: "neutral", label: "Won't do", terminal: true, next: ["open"], requires: ["reason"], optional: [], by: null },
  { id: "duplicate", retired: false, tone: "neutral", label: "Duplicate", terminal: true, next: ["open"], requires: ["duplicate_of"], optional: [], by: null },
]), (e) => e.id);

/**
 * A post is owned by exactly one person, and never by a GM. Take = assign to yourself;
 * a triager may assign to any eligible member.
 */
export const assigneeMinRole: Role = "maintainer";

/** The lowest role that may triage. */
export const triageMinRole: Role = "maintainer";

/** The deck's arrangements. */
export const deck: Deck = canonFreeze<Deck>({ layouts: ["4:1", "2:2"], maxHidden: 2 });

/** The deck's columns, left to right. */
export const columns: CanonTable<ColumnId, Column> = canonTable(canonFreeze<ReadonlyArray<Column>>([
  { id: "unclaimed", retired: false, label: "Unclaimed", icon: "inbox", statuses: ["open"], assigneeFilter: false, hideable: true },
  { id: "taken", retired: false, label: "Taken", icon: "hand", statuses: ["taken"], assigneeFilter: true, hideable: true },
  { id: "fixed", retired: false, label: "Fixed, to verify", icon: "check", statuses: ["fixed"], assigneeFilter: false, hideable: true },
  { id: "done", retired: false, label: "Done", icon: "archive", statuses: ["verified", "wont_do", "duplicate"], assigneeFilter: false, hideable: true },
]), (e) => e.id);

/** How bad a triaged post is. */
export const severities: CanonTable<SeverityId, Severity> = canonTable(canonFreeze<ReadonlyArray<Severity>>([
  { id: "low", retired: false, tone: "neutral", label: "Low", default: false },
  { id: "normal", retired: false, tone: "info", label: "Normal", default: true },
  { id: "critical", retired: false, tone: "danger", label: "Critical", default: false },
]), (e) => e.id);

/** The headers of the area picker. */
export const areaGroups: CanonTable<AreaGroupId, AreaGroup> = canonTable(canonFreeze<ReadonlyArray<AreaGroup>>([
  { id: "in_game", retired: false, label: "In game" },
  { id: "out_game", retired: false, label: "Out of game" },
  { id: "internal", retired: false, label: "Internal" },
]), (e) => e.id);

/** Where a post was seen. */
export const areas: CanonTable<AreaId, Area> = canonTable(canonFreeze<ReadonlyArray<Area>>([
  { id: "game", retired: false, group: "in_game", tone: "series-1", icon: "gamepad", label: "Game", hint: "Anything you saw while playing.", minRole: "gm_junior", routesTo: ["game_server", "client", "resource", "balance"] },
  { id: "balance", retired: false, group: "in_game", tone: "series-1", icon: "scale", label: "Balance", hint: "Nothing is broken, the numbers feel wrong.", minRole: "gm_junior", routesTo: [] },
  { id: "website", retired: false, group: "out_game", tone: "series-2", icon: "globe", label: "Website", hint: "The site, accounts, rankings, donations and payments.", minRole: "gm_junior", routesTo: [] },
  { id: "resource_studio", retired: false, group: "internal", tone: "series-3", icon: "layers", label: "Resource Studio", hint: null, minRole: "maintainer", routesTo: [] },
  { id: "game_server", retired: false, group: "in_game", tone: "series-1", icon: "server", label: "Game server", hint: null, minRole: "admin", routesTo: [] },
  { id: "client", retired: false, group: "in_game", tone: "series-1", icon: "monitor", label: "Game client", hint: null, minRole: "maintainer", routesTo: [] },
  { id: "resource", retired: false, group: "in_game", tone: "series-1", icon: "database", label: "Game data (Resource)", hint: null, minRole: "maintainer", routesTo: [] },
  { id: "sovcommon", retired: false, group: "internal", tone: "series-3", icon: "package", label: "sovcommon", hint: null, minRole: "admin", routesTo: [] },
  { id: "admin_panel", retired: false, group: "internal", tone: "series-2", icon: "shield", label: "Admin panel", hint: null, minRole: "admin", routesTo: [] },
  { id: "analytics", retired: false, group: "internal", tone: "series-2", icon: "bar-chart", label: "Analytics panel", hint: null, minRole: "admin", routesTo: [] },
  { id: "team_board", retired: false, group: "internal", tone: "series-2", icon: "columns", label: "Team board", hint: "This board itself: something broken or missing here.", minRole: "gm_junior", routesTo: [] },
  { id: "internal", retired: false, group: "internal", tone: "series-4", icon: "terminal", label: "Internal (sov, boxes, deploy)", hint: null, minRole: "admin", routesTo: [] },
]), (e) => e.id);

/**
 * A new post starts here: the single status of the first column. The deck has at least
 * two columns (`maxHidden` >= 1 is below their count), so `first()!` cannot fail.
 */
export const initialStatus: StatusId = "open";

/**
 * The severity a triaged post gets unless the triager picks another. Exactly one
 * exists: see the `default` check below.
 */
export const defaultSeverity: SeverityId = "normal";

const CAN_TRANSITION: ReadonlyArray<boolean> = canonFreeze<ReadonlyArray<boolean>>([
  false, true, false, false, true, true,
  true, false, true, false, true, true,
  true, false, false, true, false, false,
  true, false, false, false, false, false,
  true, false, false, false, false, false,
  true, false, false, false, false, false,
]);

/** sovcommon's CanTransition. */
export function canTransition(from: StatusId, to: StatusId): boolean {
  return CAN_TRANSITION[StatusIdIndex[from] * 6 + StatusIdIndex[to]];
}

const COLUMN_OF: ReadonlyArray<ColumnId | null> = canonFreeze<ReadonlyArray<ColumnId | null>>([
  "unclaimed", "taken", "fixed", "done", "done", "done",
]);

/**
 * sovcommon's ColumnOf. `none` for a status no active column claims (only a retired
 * status can be in that case), like the `(Column, bool)` it replaces.
 */
export function columnOf(s: StatusId): ColumnId | null {
  return COLUMN_OF[StatusIdIndex[s]];
}

const AREAS_VISIBLE_TO: ReadonlyArray<ReadonlyArray<AreaId>> = canonFreeze<ReadonlyArray<ReadonlyArray<AreaId>>>([
  [],
  ["game", "balance", "website", "team_board"],
  ["game", "balance", "website", "team_board"],
  ["game", "balance", "website", "resource_studio", "client", "resource", "team_board"],
  ["game", "balance", "website", "resource_studio", "client", "resource", "team_board"],
  ["game", "balance", "website", "resource_studio", "game_server", "client", "resource", "sovcommon", "admin_panel", "analytics", "team_board", "internal"],
]);

/** sovcommon's AreasVisibleTo: minRole gates viewing and posting. */
export function areasVisibleTo(role: Role): ReadonlyArray<AreaId> {
  return AREAS_VISIBLE_TO[RoleIndex[role]];
}

const GROUPED_AREAS_VISIBLE_TO: ReadonlyArray<ReadonlyArray<AreaSection>> = canonFreeze<ReadonlyArray<ReadonlyArray<AreaSection>>>([
  [],
  [{ group: "in_game", areas: ["game", "balance"] }, { group: "out_game", areas: ["website"] }, { group: "internal", areas: ["team_board"] }],
  [{ group: "in_game", areas: ["game", "balance"] }, { group: "out_game", areas: ["website"] }, { group: "internal", areas: ["team_board"] }],
  [{ group: "in_game", areas: ["game", "balance", "client", "resource"] }, { group: "out_game", areas: ["website"] }, { group: "internal", areas: ["resource_studio", "team_board"] }],
  [{ group: "in_game", areas: ["game", "balance", "client", "resource"] }, { group: "out_game", areas: ["website"] }, { group: "internal", areas: ["resource_studio", "team_board"] }],
  [{ group: "in_game", areas: ["game", "balance", "game_server", "client", "resource"] }, { group: "out_game", areas: ["website"] }, { group: "internal", areas: ["resource_studio", "sovcommon", "admin_panel", "analytics", "team_board", "internal"] }],
]);

/** sovcommon's GroupedAreasVisibleTo: headers only for groups with a visible area. */
export function groupedAreasVisibleTo(role: Role): ReadonlyArray<AreaSection> {
  return GROUPED_AREAS_VISIBLE_TO[RoleIndex[role]];
}
