// GENERATED by canon from features/copies/. DO NOT EDIT.
#pragma once

#include <cstddef>
#include <memory>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

#include <nlohmann/json_fwd.hpp>

#include "canon_runtime.h"
#include "../base/base.gen.h"

namespace features::copies {

/// Fingerprint of the schema of badges.json (types, wire names, units), not of
/// its values. The loader refuses a file built from another schema.
inline constexpr std::string_view kBadgesSchema = "features.copies.Badge@e275e30d";

class Badge;
class Badges;

namespace detail {
struct CopiesAccess;
struct CopiesMake;
bool Decode(const nlohmann::json& v, canon::json::Decoder& dec, Badge& out);
}  // namespace detail

/// A badge.
class Badge {
public:
    const std::string& GetId() const { return id_; }
    bool GetRetired() const { return retired_; }
    /// Its colour.
    ::features::copies::base::Tone GetTone() const { return tone_; }

private:
    friend struct detail::CopiesAccess;
    friend struct detail::CopiesMake;
    friend bool detail::Decode(const nlohmann::json&, canon::json::Decoder&, Badge&);

    std::string id_;
    bool retired_ = false;
    ::features::copies::base::Tone tone_{};
};

namespace detail {
struct CopiesMake {
    static ::features::copies::Badge Badge(::features::copies::base::Tone tone_) {
        ::features::copies::Badge out;
        out.tone_ = std::move(tone_);
        return out;
    }

    static ::features::copies::Badge Entry_Badge(::features::copies::Badge record, std::string id, bool retired) {
        ::features::copies::Badge out;
        out = std::move(record);
        out.id_ = std::move(id);
        out.retired_ = retired;
        return out;
    }
};
}  // namespace detail

/// Every badge.
class Badges {
public:
    Badges() = default;
    Badges(const Badges&) = delete;
    Badges& operator=(const Badges&) = delete;
    Badges(Badges&&) = default;
    Badges& operator=(Badges&&) = default;

    static std::shared_ptr<const Badges> Load(const std::string& path, std::string& error);
    size_t Len() const { return rows_.All().size(); }
    const Badge& At(size_t i) const { return rows_.At(i); }
    const std::vector<Badge>& All() const { return rows_.All(); }
    /// Binary search by id. Never allocates; nullptr when absent.
    const Badge* Find(std::string_view id) const { return rows_.Find(id); }

private:
    friend struct detail::CopiesAccess;

    canon::KeyedList<std::string, Badge> rows_;
};

}  // namespace features::copies
