// GENERATED by canon from features/copies/. DO NOT EDIT.
#include "copies.gen.h"

#include <cstddef>
#include <memory>
#include <string>
#include <utility>
#include <vector>

#include "canon_runtime_json.h"

namespace features::copies {

namespace detail {

bool Decode(const nlohmann::json& v, canon::json::Decoder& dec, Badge& out) {
    if (!canon::json::detail::Keys(v, dec, {"$id", "$retired", "tone"})) return false;
    dec.Enum(v, "tone", &::features::copies::base::ToneFromWire, out.tone_);
    return dec.Ok();
}

struct CopiesAccess {
    static bool LoadBadges(const std::string& path, Badges& out, std::string& error) {
        std::string text;
        nlohmann::json doc;
        canon::json::Float32Tokens tokens;
        if (!canon::json::ReadFile(path, text, error)) return false;
        if (!canon::json::ParseDataFile(path, text, kBadgesSchema, doc, error, tokens)) return false;
        canon::json::Decoder dec(path, tokens);
        const nlohmann::json* rows = dec.Array(doc, "rows");
        if (rows == nullptr) return error = dec.Error(), false;
        std::vector<Badge> values(rows->size());
        std::vector<std::string> keys(rows->size());
        for (size_t i = 0; i < rows->size(); ++i) {
            dec.Push("rows[" + std::to_string(i) + "]");
            canon::json::detail::Row((*rows)[i], dec, values[i].id_, values[i].retired_);
            Decode((*rows)[i], dec, values[i]);
            dec.Pop();
            if (!dec.Ok()) return error = dec.Error(), false;
            keys[i] = values[i].id_;
        }
        if (!canon::json::detail::CheckUnique(keys, dec, "$id", "rows", [](const auto& k) { return canon::json::detail::KeyToken(k); })) return error = dec.Error(), false;
        out.rows_ = canon::KeyedList<std::string, Badge>::FromRows(std::move(values), std::move(keys));
        return true;
    }
};

}  // namespace detail

std::shared_ptr<const Badges> Badges::Load(const std::string& path, std::string& error) {
    auto out = std::make_shared<Badges>();
    if (!detail::CopiesAccess::LoadBadges(path, *out, error)) return nullptr;
    return out;
}

}  // namespace features::copies
