// GENERATED by canon from sovcommon/roles/. DO NOT EDIT.

// ---------------------------------------------------------------------------
// canon runtime, TypeScript v1 (CODEGEN.md §8.2). Identical in every generated file.
// ---------------------------------------------------------------------------

/** An error the Canon evaluator would also report, with its code ("E4101"). */
export class CanonEvalError extends Error {
  readonly code: string;
  constructor(code: string, message: string) {
    super(code + ": " + message);
    this.name = "CanonEvalError";
    this.code = code;
  }
}

/** A table or keyed list: entries in source order, lookup by key. */
export interface CanonTable<K, T> {
  readonly length: number;
  readonly all: ReadonlyArray<T>;
  at(i: number): T;
  find(key: K): T | null;
}
// ---------------------------------------------------------------------------

/**
 * The website.website_account.role literals. Declaration order IS the rank:
 * `gm_junior < maintainer` is true, and nothing else may hard-code a number.
 *
 * Today this ladder is written three times (roles.go, roles.ts and the SQL CHECK
 * constraint) and kept in sync by comments. Here it is written once, and Go and TS
 * are generated from it.
 */
export type Role = "member" | "gm_junior" | "gm_senior" | "maintainer" | "owner" | "admin";
export const RoleMembers: ReadonlyArray<Role> = Object.freeze(["member", "gm_junior", "gm_senior", "maintainer", "owner", "admin"]);
export const RoleNames: Readonly<Record<Role, string>> = Object.freeze({ member: "member", gm_junior: "gm_junior", gm_senior: "gm_senior", maintainer: "maintainer", owner: "owner", admin: "admin" });
export const RoleIndex: Readonly<Record<Role, number>> = Object.freeze({ member: 0, gm_junior: 1, gm_senior: 2, maintainer: 3, owner: 4, admin: 5 });
