// GENERATED by canon from sovcommon/ui/. DO NOT EDIT.

// ---------------------------------------------------------------------------
// canon runtime, TypeScript v1 (CODEGEN.md §8.2). Identical in every generated file.
// ---------------------------------------------------------------------------

/** An error the Canon evaluator would also report, with its code ("E4101"). */
export class CanonEvalError extends Error {
  readonly code: string;
  constructor(code: string, message: string) {
    super(code + ": " + message);
    this.name = "CanonEvalError";
    this.code = code;
  }
}

/** A table or keyed list: entries in source order, lookup by key. */
export interface CanonTable<K, T> {
  readonly length: number;
  readonly all: ReadonlyArray<T>;
  at(i: number): T;
  find(key: K): T | null;
}
// ---------------------------------------------------------------------------

/**
 * A semantic or qualitative colour slot. Each one resolves to a --color-* token that
 * tokens.css defines for dark and light, with its -soft background. No colour value
 * lives in config.
 *
 * Semantic tones are reserved for meaning (status, severity, flags, intent).
 * Qualitative series slots tell families apart, always together with icon + label.
 */
export type Tone = "warning" | "info" | "accent" | "success" | "neutral" | "danger" | "series-1" | "series-2" | "series-3" | "series-4" | "series-5" | "series-6";
export const ToneMembers: ReadonlyArray<Tone> = Object.freeze(["warning", "info", "accent", "success", "neutral", "danger", "series-1", "series-2", "series-3", "series-4", "series-5", "series-6"]);
export const ToneNames: Readonly<Record<Tone, string>> = Object.freeze({ warning: "warning", info: "info", accent: "accent", success: "success", neutral: "neutral", danger: "danger", "series-1": "series_1", "series-2": "series_2", "series-3": "series_3", "series-4": "series_4", "series-5": "series_5", "series-6": "series_6" });
export const ToneIndex: Readonly<Record<Tone, number>> = Object.freeze({ warning: 0, info: 1, accent: 2, success: 3, neutral: 4, danger: 5, "series-1": 6, "series-2": 7, "series-3": 8, "series-4": 9, "series-5": 10, "series-6": 11 });

/**
 * Icons sovcommon exports (icons.ts). An icon that is not listed here is a type
 * error wherever it is used, so `make check` no longer has to scrape TypeScript.
 */
export type Icon = "alert-triangle" | "archive" | "bar-chart" | "check" | "columns" | "database" | "gamepad" | "globe" | "hand" | "inbox" | "layers" | "lightbulb" | "lock" | "monitor" | "package" | "scale" | "server" | "shield" | "terminal";
export const IconMembers: ReadonlyArray<Icon> = Object.freeze(["alert-triangle", "archive", "bar-chart", "check", "columns", "database", "gamepad", "globe", "hand", "inbox", "layers", "lightbulb", "lock", "monitor", "package", "scale", "server", "shield", "terminal"]);
export const IconNames: Readonly<Record<Icon, string>> = Object.freeze({ "alert-triangle": "alert_triangle", archive: "archive", "bar-chart": "bar_chart", check: "check", columns: "columns", database: "database", gamepad: "gamepad", globe: "globe", hand: "hand", inbox: "inbox", layers: "layers", lightbulb: "lightbulb", lock: "lock", monitor: "monitor", package: "package", scale: "scale", server: "server", shield: "shield", terminal: "terminal" });
export const IconIndex: Readonly<Record<Icon, number>> = Object.freeze({ "alert-triangle": 0, archive: 1, "bar-chart": 2, check: 3, columns: 4, database: 5, gamepad: 6, globe: 7, hand: 8, inbox: 9, layers: 10, lightbulb: 11, lock: 12, monitor: 13, package: 14, scale: 15, server: 16, shield: 17, terminal: 18 });
