// GENERATED by canon from features/copies/base/. DO NOT EDIT.
#include "base.gen.h"

#include "canon_runtime_json.h"

namespace features::copies::base {

namespace detail {

struct BaseAccess {
};

}  // namespace detail

}  // namespace features::copies::base
