// GENERATED by canon from features/copies/base/. DO NOT EDIT.
#pragma once

#include <array>
#include <cstdint>
#include <optional>
#include <string_view>

#include "canon_runtime.h"

namespace features::copies::base {

/// A colour.
enum class Tone : uint8_t {
    /// Warm.
    red,
    /// Cold.
    blue,
};

inline constexpr std::array<Tone, 2> kToneMembers = {Tone::red, Tone::blue};

inline std::string_view ToName(Tone v) {
    switch (v) {
    case Tone::red: return "red";
    case Tone::blue: return "blue";
    }
    return {};
}

inline std::string_view ToWire(Tone v) {
    switch (v) {
    case Tone::red: return "red";
    case Tone::blue: return "blue";
    }
    return {};
}

inline std::optional<Tone> ToneFromWire(std::string_view wire) {
    if (wire == "red") return Tone::red;
    if (wire == "blue") return Tone::blue;
    return std::nullopt;
}

namespace detail {
struct BaseAccess;
}  // namespace detail

}  // namespace features::copies::base
