// GENERATED by Tools/vocab/generate_vocab.py from Server/Vocab/upgradeType.json -- do not edit.
#define Normal 1
#define Ultimate 2
#define Jewelry 3
#define Piercing 4
#define Element 5
#define Rarity 6
