package catalog

import "regexp"

// The tables the generator reads, identified by their exact header rows.
const (
	typesHeader    = "| Type | Go parameter | Rendering |"
	kindsHeader    = "| Kind | Word | Used by |"
	runtimeHeader  = "| Code | Text |"
	codesHeader    = "| Code | Severity | Package | Owner | Meaning |"
	messagesHeader = "| Code | Variant | Args | Template |"
	planHeader     = "| Package (under `internal/` unless noted) | Owns | Implements | Consumes |"
)

// codeSectionHeaders are the two tables of a code-range section, in order.
var codeSectionHeaders = []string{codesHeader, messagesHeader}

// Column indexes of the tables above.
const (
	colCode        = 0
	colSeverity    = 1
	colPackage     = 2
	colOwner       = 3
	colMeaning     = 4
	colVariant     = 1
	colArgs        = 2
	colTemplate    = 3
	colTypeName    = 0
	colTypeGo      = 1
	colKindName    = 0
	colKindWord    = 1
	colKindUsedBy  = 2
	colRuntimeText = 1
)

// Markdown syntax.
const (
	lineBreak      = "\n"
	sectionPrefix  = "## "
	codeFence      = "```"
	cellSep        = "|"
	sepChars       = "|-"
	backtick       = "`"
	escapeChar     = '\\'
	noneCell       = "-"
	listSep        = ", "
	argSep         = ":"
	titleSep       = ":"
	rangeDash      = "–"
	codeSpanStride = 2
)

// Template syntax (ERRORS.md §1.2): the escapes are read before placeholders.
const (
	openBrace  = "{"
	closeBrace = "}"
)

var templateEscapes = []string{"{{", "}}", `\\`, `\n`}

// The package table of IMPLEMENTATION-PLAN.md.
const (
	pathSep     = "/"
	internalDir = "internal/"
	genPackage  = "gen"
)

// Catalogue rules (ERRORS.md §1.1 to §2.1).
const (
	severityError   = "error"
	severityWarning = "warning"
	severityRuntime = "runtime"
	warningLetter   = 'W'
	kindType        = "Kind"
	maxArgs         = 4
	fmtAt           = "line %d: %s"
)

var severities = []string{severityError, severityWarning, severityRuntime}

// retiredCodes are the numbers ERRORS.md says are never reused, and the two it says were
// referenced but never defined.
var retiredCodes = []string{"E1624", "E1625", "E8016", "E3014", "E3319"}

// reservedNames are Go keywords and predeclared identifiers, which no argument may be named,
// and span, the constructors' first parameter.
var reservedNames = []string{
	"break", "case", "chan", "const", "continue", "default", "defer", "else", "fallthrough",
	"for", "func", "go", "goto", "if", "import", "interface", "map", "package", "range",
	"return", "select", "struct", "switch", "type", "var",
	"any", "bool", "byte", "comparable", "complex64", "complex128", "error", "float32",
	"float64", "int", "int8", "int16", "int32", "int64", "rune", "string", "uint", "uint8",
	"uint16", "uint32", "uint64", "uintptr", "true", "false", "iota", "nil",
	"append", "cap", "clear", "close", "complex", "copy", "delete", "imag", "len", "make",
	"max", "min", "new", "panic", "print", "println", "real", "recover",
	"span",
}

var (
	reCode       = regexp.MustCompile(`^[EW][0-9]{4}$`)
	reLowerCamel = regexp.MustCompile(`^[a-z][A-Za-z0-9]*$`)
	reUpperCamel = regexp.MustCompile(`^[A-Z][A-Za-z0-9]*$`)
	reRangeTitle = regexp.MustCompile(`^[EW][0-9]+x+`)
	reRangeBound = regexp.MustCompile(`^([EW])([0-9]+)x+$`)
	reCount      = regexp.MustCompile(`^The catalogue holds ([0-9]+) codes: ([0-9]+) errors, ([0-9]+) warnings and ([0-9]+) run-time codes, with ([0-9]+) messages\.$`)
)

// Submatch groups of reRangeBound and reRuntimeCall.
const (
	rangeLetterGroup = 1
	rangeDigitsGroup = 2
	runtimeCodeGroup = 1
	runtimeTextGroup = 2
)

// The runtime helper texts: files in a directory named runtime; the calls that signal a code.
const (
	walkRoot   = "."
	runtimeDir = "runtime"
	allMatches = -1
)

var (
	reRuntimeCallStart = regexp.MustCompile(`\b(?:Fail|OnEvalError|canonFail)\(\s*"`)
	reRuntimeCall      = regexp.MustCompile(`^(?:Fail|OnEvalError|canonFail)\(\s*"([EW][0-9]{4})"\s*,\s*"((?:[^"\\]|\\.)*)"\s*\)`)
)

// Generated names.
const (
	argTypePrefix     = "ArgType"
	kindPrefix        = "Kind"
	samplePrefix      = "sample"
	constructorPrefix = "At"
	diagQualifier     = "diag."
	fmtCodeDoc        = "%s: %s (%s)."
)

// generated lists the files Generate writes, with their templates.
var generated = []struct{ name, text string }{
	{name: "codes.go", text: codesTemplate},
	{name: "codes_test.go", text: constructedTemplate},
}

const generatedHeader = "// Code generated by diaggen from spec/ERRORS.md. DO NOT EDIT.\n\npackage diag\n"

const codesTemplate = generatedHeader + `
import "github.com/fantasim/canonlang/internal/source"

// Severity is how much a finding weighs: an error blocks emission, a warning does not, and a
// runtime code is signalled by generated code, never reported by canon.
type Severity uint8

// The severities of ERRORS.md.
const (
	Error Severity = iota
	Warning
	Runtime
)

// Code is a diagnostic code, such as "E3501".
type Code string

// Def is the registry entry of one code.
type Def struct {
	Code     Code
	Severity Severity
	Package  string    // the owning package of the IMPLEMENTATION-PLAN.md package table
	Variants []Variant // one per message row, in table order
}

// Variant is one message of a code.
type Variant struct {
	Name     string // "" for a code with one message
	Args     []Arg  // in constructor order
	Template string // the template as ERRORS.md writes it, escapes kept
}

// Arg is one typed argument of a message.
type Arg struct {
	Name string
	Type ArgType
}

// ArgType is the type of a message argument.
type ArgType uint8

// The argument types of ERRORS.md, in table order.
const (
{{- range $i, $t := .Types}}
	{{$t.Const}}{{if eq $i 0}} ArgType = iota{{end}}
{{- end}}
)

// Kind is one word of a closed set that a message argument takes.
type Kind uint8

// The kinds of ERRORS.md, in table order.
const (
{{- range $i, $k := .Kinds}}
	{{$k.Const}}{{if eq $i 0}} Kind = iota{{end}}
{{- end}}
)

var severityNames = [...]string{"error", "warning", "runtime"}

var argTypeNames = [...]string{
{{- range .Types}}
	{{printf "%q" .Name}},
{{- end}}
}

var kindNames = [...]string{
{{- range .Kinds}}
	{{printf "%q" .Name}},
{{- end}}
}

var kindWords = [...]string{
{{- range .Kinds}}
	{{printf "%q" .Word}},
{{- end}}
}

// String is the severity as ERRORS.md writes it.
func (s Severity) String() string { return nameAt(severityNames[:], int(s)) }

// String is the argument type's name in ERRORS.md.
func (t ArgType) String() string { return nameAt(argTypeNames[:], int(t)) }

// String is the kind's name in ERRORS.md.
func (k Kind) String() string { return nameAt(kindNames[:], int(k)) }

// Word is what a Kind argument renders as.
func (k Kind) Word() string { return nameAt(kindWords[:], int(k)) }

func nameAt(names []string, i int) string {
	if i < 0 || i >= len(names) {
		return ""
	}
	return names[i]
}

// Registry is every code of ERRORS.md, sorted by code.
var Registry = []Def{
{{- range .Defs}}
	{
		Code: {{printf "%q" .Code}}, Severity: {{.Severity}}, Package: {{printf "%q" .Package}},
		Variants: []Variant{
		{{- range .Variants}}
			{ {{- if .Name}}Name: {{printf "%q" .Name}}, {{end}}{{if .Args}}Args: []Arg{ {{- range .Args}}{Name: {{printf "%q" .Name}}, Type: {{.Const}}}, {{end}}}, {{end}}Template: {{.Quoted}}},
		{{- end}}
		},
	},
{{- end}}
}
{{range $d := .Defs}}
// {{$d.Doc}}
var {{$d.Code}} code{{$d.Code}}

type code{{$d.Code}} struct{}

// Def is the registry entry of {{$d.Code}}.
func (code{{$d.Code}}) Def() *Def { return &Registry[{{$d.Index}}] }
{{if not $d.Runtime}}{{range $v := $d.Variants}}
// {{$v.Method}} reports: {{$v.Source}}
func (code{{$d.Code}}) {{$v.Method}}(span source.Span{{range $v.Args}}, {{.Name}} {{.GoType}}{{end}}) *Builder {
	return newBuilder(&Registry[{{$d.Index}}], {{$v.Index}}, span{{range $v.Args}}, {{.Name}}{{end}})
}
{{end}}{{end}}{{end}}`

const constructedTemplate = generatedHeader + `
// constructed holds one builder per reported message, in Registry order, each built by its
// constructor from the samples of builder_test.go.
var constructed = []*Builder{
{{- range .Calls}}
	{{.Code}}.{{.Method}}(sampleSpan{{range .Samples}}, {{.}}{{end}}),
{{- end}}
}
`
