// GENERATED by canon from features/copies/base/. DO NOT EDIT.

// ---------------------------------------------------------------------------
// canon runtime, TypeScript v1 (CODEGEN.md §8.2). Identical in every generated file.
// ---------------------------------------------------------------------------

/** An error the Canon evaluator would also report, with its code ("E4101"). */
export class CanonEvalError extends Error {
  readonly code: string;
  constructor(code: string, message: string) {
    super(code + ": " + message);
    this.name = "CanonEvalError";
    this.code = code;
  }
}

/** A table or keyed list: entries in source order, lookup by key. */
export interface CanonTable<K, T> {
  readonly length: number;
  readonly all: ReadonlyArray<T>;
  at(i: number): T;
  find(key: K): T | null;
}
// ---------------------------------------------------------------------------

/** A colour. */
export type Tone =
  /** Warm. */
  | "red"
  /** Cold. */
  | "blue";
export const ToneMembers: ReadonlyArray<Tone> = Object.freeze(["red", "blue"]);
export const ToneNames: Readonly<Record<Tone, string>> = Object.freeze({ red: "red", blue: "blue" });
export const ToneIndex: Readonly<Record<Tone, number>> = Object.freeze({ red: 0, blue: 1 });
