// GENERATED by canon from features/copies/. DO NOT EDIT.
import * as features_copies_base from "./base.js";

// ---------------------------------------------------------------------------
// canon runtime, TypeScript v1 (CODEGEN.md §8.2). Identical in every generated file.
// ---------------------------------------------------------------------------

/** An error the Canon evaluator would also report, with its code ("E4101"). */
export class CanonEvalError extends Error {
  readonly code: string;
  constructor(code: string, message: string) {
    super(code + ": " + message);
    this.name = "CanonEvalError";
    this.code = code;
  }
}

/** A table or keyed list: entries in source order, lookup by key. */
export interface CanonTable<K, T> {
  readonly length: number;
  readonly all: ReadonlyArray<T>;
  at(i: number): T;
  find(key: K): T | null;
}

/** A row of a table: its record, with this table's id and retired flag present. */
export type CanonRow<T, K> = Omit<T, "id" | "retired"> & { readonly id: K; readonly retired: boolean };

function canonTable<K, T>(rows: ReadonlyArray<T>, keyOf: (row: T) => K): CanonTable<K, T> {
  const index = new Map<K, number>();
  rows.forEach((row, i) => index.set(keyOf(row), i));
  return Object.freeze({
    length: rows.length,
    all: rows,
    at: (i: number): T => rows[i],
    find: (key: K): T | null => {
      const i = index.get(key);
      return i === undefined ? null : rows[i];
    },
  });
}

/** Deep-freezes plain objects and arrays (CanonMaps are already read-only). */
function canonFreeze<T>(x: T): T {
  if (typeof x === "object" && x !== null && !Object.isFrozen(x)) {
    Object.freeze(x);
    for (const v of Object.values(x)) canonFreeze(v);
  }
  return x;
}

/** Checks the "$schema" of a data file against the fingerprint compiled in. */
function canonEnvelope(json: unknown, schema: string, name: string): Record<string, unknown> {
  const doc = json as Record<string, unknown> | null;
  const got = doc !== null && typeof doc === "object" && typeof doc["$schema"] === "string" ? doc["$schema"] : "<none>";
  if (got !== schema) {
    throw new Error(name + ": built from schema " + got + ", this binary expects " + schema + ". Rebuild the data or deploy the matching binary");
  }
  return doc as Record<string, unknown>;
}
// ---------------------------------------------------------------------------

export type BadgeId = string;

/** A badge. */
export interface Badge {
  readonly id?: BadgeId;
  readonly retired?: boolean;
  /** Its colour. */
  readonly tone: features_copies_base.Tone;
}

export const badgesSchema = "features.copies.Badge@e275e30d";

const decOrder = Symbol.for("canon.order");

const decTokenKey = Symbol.for("canon.token");

/** A number token with a fraction or an exponent, as parse reads it: its exact text, under a key every generated file shares. */
function decToken(text: string): unknown {
  return Object.freeze(Object.defineProperty({}, decTokenKey, { value: text }));
}

/** Throws the failure at path. */
function decFail(path: string, message: string): never {
  throw new Error((path === "" ? "/" : path) + ": " + message);
}

function decGet(o: Record<string, unknown>, key: string): unknown {
  return Object.prototype.hasOwnProperty.call(o, key) ? o[key] : undefined;
}

function decIsObject(raw: unknown): raw is Record<string, unknown> {
  return typeof raw === "object" && raw !== null && !Array.isArray(raw) && !Reflect.has(raw, decTokenKey);
}

function decObject(raw: unknown, path: string): Record<string, unknown> {
  if (!decIsObject(raw)) decFail(path, "expected an object");
  return raw;
}

function decArray(raw: unknown, path: string): ReadonlyArray<unknown> {
  if (!Array.isArray(raw)) decFail(path, "expected an array");
  return raw;
}

function decBool(raw: unknown, path: string): boolean {
  if (typeof raw !== "boolean") decFail(path, "expected a boolean");
  return raw;
}

function decString(raw: unknown, path: string): string {
  if (typeof raw !== "string") decFail(path, "expected a string");
  return raw;
}

function decEnum<T extends string>(raw: unknown, path: string, members: ReadonlyArray<T>): T {
  const m = members.find((x) => x === raw);
  if (m === undefined) decFail(path, "unknown member");
  return m;
}

function decList<T>(raw: unknown, path: string, read: (x: unknown, p: string) => T): T[] {
  return decArray(raw, path).map((x, i) => read(x, path + "/" + i));
}

function decParse(text: string): unknown {
  let i = text.charCodeAt(0) === 0xfeff ? 1 : 0;
  const number = /-?(0|[1-9][0-9]*)(\.[0-9]+)?([eE][+-]?[0-9]+)?/y;
  const escapes: Record<string, string> = { '"': '"', "\\": "\\", "/": "/", b: "\b", f: "\f", n: "\n", r: "\r", t: "\t" };
  const fail = (message: string): never => decFail("offset " + i, message);
  const ws = (): void => {
    while (i < text.length && " \t\n\r".includes(text[i])) i++;
  };
  const hex4 = (): number => {
    const h = text.slice(i, i + 4);
    if (!/^[0-9a-fA-F]{4}$/.test(h)) fail("invalid \\u escape");
    i += 4;
    return parseInt(h, 16);
  };
  const unicode = (): string => {
    const u = hex4();
    if (u >= 0xdc00 && u <= 0xdfff) fail("unpaired surrogate");
    if (u < 0xd800 || u > 0xdbff) return String.fromCharCode(u);
    if (text.slice(i, i + 2) !== "\\u") fail("unpaired surrogate");
    i += 2;
    const lo = hex4();
    if (lo < 0xdc00 || lo > 0xdfff) fail("unpaired surrogate");
    return String.fromCharCode(u, lo);
  };
  const str = (): string => {
    i++;
    let out = "";
    for (;;) {
      if (i >= text.length) fail("unterminated string");
      const c = text[i++];
      if (c === '"') return out;
      if (c < " ") fail("control character in a string");
      if (c !== "\\") {
        out += c;
      } else if (text[i] === "u") {
        i++;
        out += unicode();
      } else if (Object.prototype.hasOwnProperty.call(escapes, text[i])) {
        out += escapes[text[i++]];
      } else {
        fail("invalid escape");
      }
    }
  };
  const num = (): unknown => {
    number.lastIndex = i;
    const m = number.exec(text);
    if (m === null) return fail("invalid number");
    i += m[0].length;
    if (m[2] !== undefined || m[3] !== undefined) return decToken(m[0]);
    const n = Number(m[0]);
    return Number.isSafeInteger(n) ? n : BigInt(m[0]);
  };
  const word = (w: string, v: unknown): unknown => {
    if (!text.startsWith(w, i)) fail("invalid value");
    i += w.length;
    return v;
  };
  const sep = (close: string): boolean => {
    ws();
    if (text[i] === ",") {
      i++;
      return true;
    }
    if (text[i] !== close) fail("expected , or " + close);
    i++;
    return false;
  };
  const obj = (depth: number): unknown => {
    i++;
    const o: Record<string, unknown> = {};
    const order: string[] = [];
    ws();
    if (text[i] === "}") {
      i++;
    } else {
      do {
        ws();
        if (text[i] !== '"') fail("expected a string key");
        const k = str();
        if (Object.prototype.hasOwnProperty.call(o, k)) fail("duplicate key " + k);
        ws();
        if (text[i++] !== ":") fail("expected :");
        Object.defineProperty(o, k, { value: val(depth + 1), enumerable: true, writable: true, configurable: true });
        order.push(k);
      } while (sep("}"));
    }
    Object.defineProperty(o, decOrder, { value: order });
    return o;
  };
  const arr = (depth: number): unknown => {
    i++;
    const a: unknown[] = [];
    ws();
    if (text[i] === "]") {
      i++;
      return a;
    }
    do {
      a.push(val(depth + 1));
    } while (sep("]"));
    return a;
  };
  const val = (depth: number): unknown => {
    if (depth > 512) fail("nesting deeper than 512");
    ws();
    const c = text[i];
    if (c === "{") return obj(depth);
    if (c === "[") return arr(depth);
    if (c === '"') return str();
    if (c === "t") return word("true", true);
    if (c === "f") return word("false", false);
    if (c === "n") return word("null", null);
    return num();
  };
  const v = val(0);
  ws();
  if (i < text.length) fail("trailing content");
  return v;
}

export function decodeBadges(json: unknown): CanonTable<BadgeId, CanonRow<Badge, BadgeId>> {
  const $doc = canonEnvelope(json, badgesSchema, "badges.json");
  return canonTable(canonFreeze(decList(decGet($doc, "rows"), "/rows", ($x, $p) => readBadge($x, $p) as CanonRow<Badge, BadgeId>)), ($e) => $e.id);
}

export function parseBadges(text: string): CanonTable<BadgeId, CanonRow<Badge, BadgeId>> {
  return decodeBadges(decParse(text));
}

function readBadge($raw: unknown, $path: string, $rowId?: string): Badge {
  const $o = decObject($raw, $path);
  const $v1 = $rowId ?? decString(decGet($o, "$id"), $path + "/$id");
  const $v2 = decGet($o, "$retired") === undefined ? false : decBool(decGet($o, "$retired"), $path + "/$retired");
  const $v3: features_copies_base.Tone = decEnum(decGet($o, "tone"), $path + "/tone", features_copies_base.ToneMembers);
  return { id: $v1, retired: $v2, tone: $v3 };
}
