package gosrc

import (
	"os"
	"path/filepath"
	"testing"

	"golang.org/x/tools/go/packages"
)

// TestPkgSkipped guards against a regression like flatted.go: an npm package under
// node_modules/ that ships Go sources, which Typed()'s "./..." load also matches.
func TestPkgSkipped(t *testing.T) {
	tree := &Tree{Root: "/repo"}
	cases := []struct {
		name  string
		files []string
		want  bool
	}{
		{"repo file", []string{"/repo/internal/x/x.go"}, false},
		{"node_modules go source", []string{"/repo/web/node_modules/flatted/golang/pkg/flatted/flatted.go"}, true},
		{"mixed is not all-skipped", []string{"/repo/internal/x/x.go", "/repo/web/node_modules/flatted/golang/pkg/flatted/flatted.go"}, false},
		{"generated golden", []string{"/repo/examples/pipeline/expected/go/potions.gen.go"}, true},
		{"no files", nil, false},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			p := &packages.Package{GoFiles: c.files}
			if got := tree.pkgSkipped(p); got != c.want {
				t.Errorf("pkgSkipped(%v) = %v, want %v", c.files, got, c.want)
			}
		})
	}
}

func TestDropSkipped(t *testing.T) {
	tree := &Tree{Root: "/repo"}
	pkgs := []*packages.Package{
		{PkgPath: "example.com/repo/internal/x", GoFiles: []string{"/repo/internal/x/x.go"}},
		{PkgPath: "example.com/repo/web/node_modules/flatted/golang/pkg/flatted", GoFiles: []string{"/repo/web/node_modules/flatted/golang/pkg/flatted/flatted.go"}},
	}
	got := tree.dropSkipped(pkgs)
	if len(got) != 1 || got[0].PkgPath != "example.com/repo/internal/x" {
		t.Errorf("dropSkipped kept %v, want only the repo package", got)
	}
}

func TestHarness(t *testing.T) {
	cases := map[string]bool{
		"cmd/e2e": true, "internal/e2e/fake": true, "internal/paystub": true,
		"internal/api": false, "cmd/server": false, ".": false,
	}
	for dir, want := range cases {
		if got := harness(dir); got != want {
			t.Errorf("harness(%q) = %v, want %v", dir, got, want)
		}
	}
}

func TestGeneratedByMarkerOrSuffix(t *testing.T) {
	dir := t.TempDir()
	files := map[string]string{
		"marked.go":  "// Code generated by canon. DO NOT EDIT.\n\npackage p\n",
		"x.gen.go":   "package p\n",
		"written.go": "package p\n",
	}
	for name, src := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(src), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	tree, errs := Parse(dir, []string{"marked.go", "x.gen.go", "written.go"})
	if len(errs) > 0 {
		t.Fatal(errs)
	}
	want := map[string]bool{"marked.go": true, "x.gen.go": true, "written.go": false}
	for _, f := range tree.Files {
		if f.Generated != want[f.Path] {
			t.Errorf("%s: Generated = %v, want %v", f.Path, f.Generated, want[f.Path])
		}
	}
}
