package progen_test

import (
	"fmt"
	"path"
	"slices"
	"strings"

	"github.com/fantasim/canonlang/internal/diag"
	"github.com/fantasim/canonlang/internal/syntax"
	"github.com/fantasim/canonlang/internal/testkit/progen"
)

// Operators on emits and generated code (CODEGEN.md §2–§5, WIRE.md §8, CONFORMANCE.md).
func emitOperators() []operator {
	e8001 := op(diag.E8001.Def().Code, "CODEGEN.md §2.4 (output not generated by canon)", unmarkedOutput)
	e8001.build = true
	e8004 := op(diag.E8004.Def().Code, "CODEGEN.md §2.8 (imported type without a go emit)", dropImportedEmit)
	e8004.many = true
	// A Range has no wire form (WIRE.md §5.9) nor Go form (CODEGEN.md §4.4): one finding per emit.
	e8151 := op(diag.E8151.Def().Code, "WIRE.md §5.9 (Range value to JSON)", withDirJSON("/// A span.\nlet ", "zzSpan", ": Range = 0..1"))
	e8151.also = []diag.Code{diag.E8012.Def().Code}
	e8152 := op(diag.E8152.Def().Code, "WIRE.md §8.1 (two outputs, one path)", collidingOutputs)
	e8152.build = true
	return []operator{
		e8001,
		op(diag.E8002.Def().Code, "CODEGEN.md §2.1 (two emits of one target)", duplicateEmit),
		op(diag.E8003.Def().Code, "CODEGEN.md §2.1 (unknown emit option)", emitOption("zzopt", ": 1")),
		e8004,
		op(diag.E8005.Def().Code, "CODEGEN.md §3.5 (colliding Go names)", collidingMember),
		op(diag.E8007.Def().Code, "CODEGEN.md §2.8 (Go output under no go_module root)", unmappedGoOut),
		op(diag.E8008.Def().Code, "CODEGEN.md §2.3 (two Go emits, one directory)", sharedGoDir),
		op(diag.E8009.Def().Code, "CODEGEN.md §2.1 (invalid mode)", emitValue("mode", "zzmode")),
		op(diag.E8010.Def().Code, "CODEGEN.md §5.2 (ordered codes decreasing)", withEmit("go", "/// A rank.\nenum ", "ZzRank", " ordered @codes(UInt8) { low = 2, high = 1 }")),
		op(diag.E8011.Def().Code, "CODEGEN.md §3.5 (@go(name:) not an identifier)", badGoName),
		op(diag.E8012.Def().Code, "CODEGEN.md §4.4 (Range field, no json emit)", goRecordField("zzSpan", ": Range = 0..1")),
		op(diag.E8013.Def().Code, "CODEGEN.md §5.10 (package fn in data mode)", withMode("go", "data", "/// Weight.\nexport fn ", "zzWeight", "(heavy: Bool) -> Int { return if heavy { 2 } else { 1 } }")),
		op(diag.E8014.Def().Code, "CODEGEN.md §5.13 (types mode, precomputed fn)", withMode("", modeTypes, "/// An answer.\nexport fn ", "zzAnswer", "() -> Int { return 42 }")),
		op(diag.E8015.Def().Code, "CODEGEN.md §2.2 (data mode Int value)", withMode("go", "data", "/// A cap.\n@menu(items)\nlet ", "zzCap", ": Int = 3")),
		op(diag.E8017.Def().Code, "CODEGEN.md §5.6 (list branch)", withEmit("go", "/// Kinds.\nenum ZzKind { one, many }\n\n/// Amounts.\ntype ", "ZzAmount", "(k: ZzKind) = match k { one => Int, many => [Int] }")),
		op(diag.E8020.Def().Code, "CODEGEN.md §5.1 (Float constant of -0.0)", withEmit("go", "/// Zero, negative.\nconst ", "ZZ_NEG", " = -0.0")),
		op(diag.E8101.Def().Code, "CODEGEN.md §4.1 (integer past the TS range)", withoutTypes("ts", withEmit("ts", "/// Big.\nlet ", "zzBig", ": Int = 9_007_199_254_740_993"))),
		op(diag.E8104.Def().Code, "CODEGEN.md §5.12 (TS emit with inputs)", tsWithInputs),
		op(diag.E8150.Def().Code, "WIRE.md §8.1 (file out, two values)", jsonFileTwoValues),
		e8151,
		e8152,
		op(diag.E8153.Def().Code, "WIRE.md §8.1 (data value not in emit json)", dropJSONEmit),
		op(diag.E8202.Def().Code, "CODEGEN.md §5.11 (@reload on baked)", reloadBaked),
		op(diag.E9001.Def().Code, "CONFORMANCE.md §2.2 (var in a translated function)", withEmit("go", "/// Sums.\nexport fn zzBelow(n: Int) -> Int {\n  ", "var total = n", "\n  return total\n}")),
		op(diag.E9002.Def().Code, "CONFORMANCE.md §8 (lookup table too big)", withoutTypes("", withEmit("go", wideEnum()+"\n\n/// Same.\nexport fn ", "zzSame", "(x: ZzWide, y: ZzWide) -> Bool { return x == y }"))),
		op(diag.E9003.Def().Code, "CONFORMANCE.md §2.1 (optional parameter)", withEmit("go", "/// A bonus.\nexport fn zzBonus(", "level", ": Int?) -> Int { return level ?? 0 }")),
		op(diag.E9004.Def().Code, "CONFORMANCE.md §2.1 (optional result)", withEmit("go", "/// Maybe.\nexport fn zzMaybe(n: Int) -> ", "Int?", " { return n }")),
		op(diag.E9005.Def().Code, "CONFORMANCE.md §2.2 (Float in a template)", withEmit("go", "/// A label.\nexport fn zzLabel(x: Float) -> String { return \"x = {", "x", "}\" }")),
		op(diag.E9006.Def().Code, "CONFORMANCE.md §2.1 (list parameter)", withEmit("go", "/// Pick.\nexport fn zzPick(", "xs", ": [Int], n: Int) -> Int { return n }")),
		op(diag.E9007.Def().Code, "CONFORMANCE.md §2.1 (where on a parameter)", withEmit("go", "/// Half.\nexport fn zzHalf(", "n", ": Int where it % 2 == 0) -> Int { return n / 2 }")),
		op(diag.E9008.Def().Code, "CONFORMANCE.md §6.1 (translated method no test calls)", withEmit("go",
			"/// A box.\nrecord ZzBox {\n  /// Size.\n  size: Int\n\n  /// Scaled.\n  export fn ", "zzScaled", "(self, n: Int) -> Int { return size * n }\n}")),
		{code: diag.E9009.Def().Code, rule: "CONFORMANCE.md §6.5 (vector past the call-depth limit)", many: true, sites: withEmit("go",
			"/// Deep.\nexport fn ", "zzDeep", "(n: Int) -> Int {\n  return if n <= 0 { 0 } else { zzDeep(n - 1) }\n}")},
	}
}

// emitsOf are the file's emits of the target kind ("" for any).
func emitsOf(tg target, kind string) []*syntax.EmitDecl {
	var out []*syntax.EmitDecl
	for _, d := range nodes[*syntax.EmitDecl](tg) {
		if kind == "" || d.Target.Name == kind {
			out = append(out, d)
		}
	}
	return out
}

// option is an emit's option named name, or nil.
func option(d *syntax.EmitDecl, name string) *syntax.FieldItem {
	for _, it := range d.Options.Items {
		if f, ok := it.(*syntax.FieldItem); ok && f.Name.Name == name {
			return f
		}
	}
	return nil
}

func optionText(tg target, d *syntax.EmitDecl, name string) string {
	if f := option(d, name); f != nil {
		return strings.Trim(text(tg, f.Value), `"`)
	}
	return ""
}

// withEmit appends before+focus+after to every file with an emit of the target kind and no
// data-mode go emit, whose own rules (E8013, E8015, E8153) a new declaration would meet.
func withEmit(kind, before, focus, after string) func(target) []progen.Site {
	return func(tg target) []progen.Site {
		if len(emitsOf(tg, kind)) == 0 || dataMode(tg) {
			return nil
		}
		return []progen.Site{appendDecl(tg, before, focus, after)}
	}
}

// withDirJSON appends before+focus+after to every file with a directory-mode json emit, which
// writes every public value.
func withDirJSON(before, focus, after string) func(target) []progen.Site {
	return func(tg target) []progen.Site {
		for _, d := range emitsOf(tg, "json") {
			if option(d, "values") == nil && strings.HasSuffix(optionText(tg, d, "out"), "/") {
				return []progen.Site{appendDecl(tg, before, focus, after)}
			}
		}
		return nil
	}
}

// withMode appends before+focus+after to every file with an emit of the target kind in mode.
func withMode(kind, mode, before, focus, after string) func(target) []progen.Site {
	return func(tg target) []progen.Site {
		for _, d := range emitsOf(tg, kind) {
			if optionText(tg, d, "mode") == mode {
				return []progen.Site{appendDecl(tg, before, focus, after)}
			}
		}
		return nil
	}
}

// withoutTypes keeps f's sites where no kind emit ("" any) is types mode: no E8101, E8014 (CODEGEN.md §4.1, §5.10; DECISIONS 289).
func withoutTypes(kind string, f func(target) []progen.Site) func(target) []progen.Site {
	return func(tg target) []progen.Site {
		for _, p := range peers(tg) {
			for _, d := range emitsOf(p, kind) {
				if optionText(p, d, "mode") == modeTypes {
					return nil
				}
			}
		}
		return f(tg)
	}
}

func emitOption(name, rest string) func(target) []progen.Site {
	return func(tg target) []progen.Site {
		var out []progen.Site
		for _, d := range emitsOf(tg, "") {
			_, e := span(tg, d.Options.Items[len(d.Options.Items)-1])
			out = append(out, seq(1, insert(e, ", "), insert(e, name), insert(e, rest)))
		}
		return out
	}
}

func emitValue(name, value string) func(target) []progen.Site {
	return func(tg target) []progen.Site {
		var out []progen.Site
		for _, d := range emitsOf(tg, "") {
			if f := option(d, name); f != nil {
				s, e := span(tg, f.Value)
				out = append(out, site(replace(s, e, value)))
			}
		}
		return out
	}
}

// unmarkedOutput puts, where a directory-mode json emit writes a value's file, a file with no
// canon marker: the build refuses to overwrite it.
func unmarkedOutput(tg target) []progen.Site {
	var out []progen.Site
	lets := publicLets(tg)
	for _, d := range emitsOf(tg, "json") {
		dir := optionText(tg, d, "out")
		root, rest, ok := strings.Cut(strings.TrimPrefix(dir, "@"), "/")
		if !strings.HasPrefix(dir, "@") || !ok || !strings.HasSuffix(dir, "/") || len(lets) == 0 || option(d, "values") != nil {
			continue
		}
		f := option(d, "out")
		s, e := span(tg, f.Value)
		file := path.Join(outRoots+root, rest, lets[0]+".json")
		out = append(out, progen.Site{Edits: []progen.Edit{mark(tg, s, e)}, Add: map[string][]byte{file: []byte("{}\n")}})
	}
	return out
}

func duplicateEmit(tg target) []progen.Site {
	return sitesOf(tg, func(d *syntax.EmitDecl) bool { return startsLine(tg, d) && endsLine(tg, d) }, func(d *syntax.EmitDecl) progen.Site {
		s, e := span(tg, d)
		ts, te := span(tg, d.Target)
		return keeping(tg, seq(1, insert(e, "\n"+string(tg.src[s:ts])), insert(e, string(tg.src[ts:te])), insert(e, string(tg.src[te:e]))), d.Target)
	})
}

// dropImportedEmit removes a package's go emit: every type of it that an importer with a go
// emit uses is then E8004 in the importer.
func dropImportedEmit(tg target) []progen.Site {
	var out []progen.Site
	for _, d := range emitsOf(tg, "go") {
		s, e := span(tg, d)
		for _, qt := range goImporters(tg) {
			if place, ok := importerEmit(qt, tg.pkg); ok {
				out = append(out, progen.Site{Edits: []progen.Edit{replace(s, e, "")}, Elsewhere: &place, Packages: []string{qt.pkg}})
			}
		}
	}
	return out
}

// importerEmit is the target of qt's go emit, where E8004 names an imported type it cannot use;
// false when qt imports no name from pkg.
func importerEmit(qt target, pkg string) (progen.Place, bool) {
	uses := false
	for _, imp := range nodes[*syntax.Import](qt) {
		uses = uses || text(qt, imp.Path) == pkg && len(imp.Names) > 0
	}
	emits := emitsOf(qt, "go")
	if len(emits) == 0 {
		return progen.Place{}, false
	}
	s, e := span(qt, emits[0].Target)
	return progen.Place{Path: qt.path, Region: progen.Region{Start: s, End: e}}, uses
}

// goImporters are the files with a go emit of the packages that import tg's package.
func goImporters(tg target) []target {
	var out []target
	for _, q := range importers(tg) {
		for _, qt := range *tg.all {
			if qt.pkg == q && len(emitsOf(qt, "go")) > 0 {
				out = append(out, qt)
			}
		}
	}
	return out
}

// camelJoin is a name without its underscores, the next letters upper-cased (CODEGEN.md §3.2).
func camelJoin(name string) string {
	parts := strings.Split(name, "_")
	for i := 1; i < len(parts); i++ {
		if parts[i] != "" {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

// collidingMember adds, to an enum of a package with a go emit, a member whose Go name is an
// underscored member's; never to an enum a match without `_` must cover.
func collidingMember(tg target) []progen.Site {
	if len(emitsOf(tg, "go")) == 0 {
		return nil
	}
	covered := exhaustivelyMatched(tg)
	var out []progen.Site
	for _, d := range nodes[*syntax.EnumDecl](tg) {
		if slices.ContainsFunc(d.Members, func(m *syntax.EnumMember) bool { return covered[m.Name.Name] }) {
			continue
		}
		for _, m := range d.Members {
			if !strings.Contains(m.Name.Name, "_") || len(d.Annotations) > 0 {
				continue
			}
			_, e := span(tg, d.Members[len(d.Members)-1])
			out = append(out, seq(1, insert(e, ", "), insert(e, camelJoin(m.Name.Name))))
		}
	}
	return out
}

func unmappedGoOut(tg target) []progen.Site {
	if strings.HasPrefix(tg.path, "features/") || strings.HasPrefix(tg.path, "pipeline/") {
		return nil
	}
	return emitValueOf(tg, "go", "out", `"zz/go/"`)
}

func emitValueOf(tg target, kind, name, value string) []progen.Site {
	var out []progen.Site
	for _, d := range emitsOf(tg, kind) {
		if f := option(d, name); f != nil {
			s, e := span(tg, f.Value)
			out = append(out, site(replace(s, e, value)))
		}
	}
	return out
}

// sharedGoDir points a package's go emit at the directory of an imported package's.
func sharedGoDir(tg target) []progen.Site {
	var out []progen.Site
	for _, other := range importedGoEmits(tg) {
		for _, s := range emitValueOf(tg, "go", "out", `"`+other.dir+`"`) {
			s.Packages = []string{tg.pkg, other.pkg}
			out = append(out, s)
		}
	}
	return out
}

// goDir is a package and the directory its go emit writes.
type goDir struct{ pkg, dir string }

// importedGoEmits are the go emit directories of the packages tg imports that sort before its own.
func importedGoEmits(tg target) []goDir {
	var out []goDir
	for _, imp := range nodes[*syntax.Import](tg) {
		for _, other := range *tg.all {
			if other.pkg == text(tg, imp.Path) && other.pkg < tg.pkg {
				out = append(out, goDirs(other)...)
			}
		}
	}
	return out
}

// goDirs are the directories a file's go emits write.
func goDirs(tg target) []goDir {
	var out []goDir
	for _, d := range emitsOf(tg, "go") {
		if dir := optionText(tg, d, "out"); dir != "" {
			out = append(out, goDir{tg.pkg, dir})
		}
	}
	return out
}

func badGoName(tg target) []progen.Site {
	if len(emitsOf(tg, "go")) == 0 {
		return nil
	}
	return sitesOf(tg, func(r *syntax.RecordDecl) bool { return len(r.Annotations) == 0 }, func(r *syntax.RecordDecl) progen.Site {
		s, e := span(tg, r.Name)
		return seq(0, mark(tg, s, e), insert(e, ` @go(name: "1Bad")`))
	})
}

// goRecordField adds a field to the records of a file with a go emit and no json one (WIRE.md §5.9).
func goRecordField(name, rest string) func(target) []progen.Site {
	return func(tg target) []progen.Site {
		if len(emitsOf(tg, "go")) == 0 || len(emitsOf(tg, "json")) > 0 {
			return nil
		}
		return recordField("", name, rest)(tg)
	}
}

func tsWithInputs(tg target) []progen.Site {
	var out []progen.Site
	for _, f := range inputFields(tg) {
		if len(emitsOf(tg, "ts")) > 0 {
			continue
		}
		s, e := span(tg, f.Name)
		end := declEnd(tg)
		out = append(out, seq(0, mark(tg, s, e), insert(end, "\nemit ts { out: \"@web/zz.generated.ts\" }\n")))
	}
	return out
}

func jsonFileTwoValues(tg target) []progen.Site {
	var out []progen.Site
	for _, d := range emitsOf(tg, "json") {
		f := option(d, "values")
		if f == nil || !strings.HasSuffix(optionText(tg, d, "out"), ".json") || dataMode(tg) {
			continue
		}
		s, _ := span(tg, d)
		_, te := span(tg, d.Target)
		_, ve := span(tg, f.Value)
		end := declEnd(tg)
		out = append(out, seq(0, mark(tg, s, te), insert(ve-1, ", zzOther"), insert(end, "\n\n/// Other.\nlet zzOther: Int = 1\n")))
	}
	return out
}

// collidingOutputs points a file-mode json emit at the file another package's directory-mode
// json emit writes for one of its values, and builds both.
func collidingOutputs(tg target) []progen.Site {
	var out []progen.Site
	for _, d := range emitsOf(tg, "json") {
		f := option(d, "out")
		if f == nil || option(d, "values") == nil || !strings.HasSuffix(optionText(tg, d, "out"), ".json") || dataMode(tg) {
			continue // a directory-mode emit with a file out is E8150 unless it has one value (WIRE.md §8.1)
		}
		for _, w := range jsonWriters(tg) {
			s, e := span(tg, f.Value)
			collide := progen.Site{Edits: []progen.Edit{replace(s, e, fmt.Sprintf("%q", w.file))}, Packages: []string{tg.pkg, w.pkg}}
			if w.pkg > tg.pkg {
				// At the later package's emit: decision log 2026-09-24, M1.5 review calls.
				collide.Elsewhere = &w.at
			}
			out = append(out, collide)
		}
	}
	return out
}

// jsonWriter is a file another package's directory-mode json emit writes, and its out option.
type jsonWriter struct {
	pkg, file string
	at        progen.Place
}

// jsonWriters are the first value files of the other packages' directory-mode json emits.
func jsonWriters(tg target) []jsonWriter {
	var out []jsonWriter
	for _, other := range *tg.all {
		for _, od := range emitsOf(other, "json") {
			dir := optionText(other, od, "out")
			lets := publicLets(other)
			if other.pkg == tg.pkg || !strings.HasSuffix(dir, "/") || option(od, "values") != nil || len(lets) == 0 {
				continue
			}
			os, oe := span(other, option(od, "out").Value)
			at := progen.Place{Path: other.path, Region: progen.Region{Start: os, End: oe}}
			out = append(out, jsonWriter{pkg: other.pkg, file: dir + lets[0] + ".json", at: at})
		}
	}
	return out
}

func dropJSONEmit(tg target) []progen.Site {
	var out []progen.Site
	for _, g := range emitsOf(tg, "go") {
		if optionText(tg, g, "mode") != "data" {
			continue
		}
		for _, j := range emitsOf(tg, "json") {
			s, e := span(tg, j)
			for _, d := range nodes[*syntax.LetDecl](tg) {
				ns, ne := span(tg, d.Name)
				out = append(out, seq(0, mark(tg, ns, ne), replace(s, e, "")))
			}
		}
	}
	return out
}

// reloadBaked turns a data-mode go emit baked in a file with an @reload value.
func reloadBaked(tg target) []progen.Site {
	var out []progen.Site
	for _, d := range nodes[*syntax.LetDecl](tg) {
		reload := false
		for _, a := range d.Annotations {
			reload = reload || a.Name.Name == "reload"
		}
		for _, g := range emitsOf(tg, "go") {
			if f := option(g, "mode"); reload && f != nil {
				ns, ne := span(tg, d.Name)
				s, e := span(tg, f.Value)
				out = append(out, seq(0, mark(tg, ns, ne), replace(s, e, "baked")))
			}
		}
	}
	return out
}

// dataMode tells a package with an emit in data or embedded mode (E8015, E8153; CODEGEN.md §2.2).
func dataMode(tg target) bool {
	for _, p := range peers(tg) {
		for _, d := range emitsOf(p, "") {
			if m := optionText(p, d, "mode"); m == modeData || m == modeEmbedded {
				return true
			}
		}
	}
	return false
}

// wideEnum declares an enum of 257 members: a lookup over two of them has 66 049 cells.
func wideEnum() string {
	const members = 257
	names := make([]string, 0, members)
	for i := range members {
		names = append(names, fmt.Sprintf("m%d", i))
	}
	return "/// A wide enum.\nenum ZzWide { " + strings.Join(names, ", ") + " }"
}
