// Code generated by vmgen from spec/viewmodel.schema.json. DO NOT EDIT.

package vm

import "encoding/json"

// ViewModel is the view-model document (VIEWMODEL.md §12.1).
type ViewModel struct {
	Schema   string                 `json:"$schema"`
	Package  string                 `json:"package"`
	Language string                 `json:"language"`
	Requires []string               `json:"requires"`
	Types    map[string]TypeDef     `json:"types"`
	Views    map[string]View        `json:"views"`
	Values   map[string]Value       `json:"values"`
	Usage    map[string]Usage       `json:"usage"`
	Search   map[string]SearchIndex `json:"search"`
	Assets   map[string]Asset       `json:"assets"`
	Units    map[string]Unit        `json:"units"`
	Widgets  map[string]Widget      `json:"widgets"`
	Studio   *Studio                `json:"studio,omitzero"`
	I18N     I18N                   `json:"i18n"`
	Findings []Finding              `json:"findings"`
}

// TypeDef is #/$defs/typeDef of spec/viewmodel.schema.json, its 4 branches in one struct.
type TypeDef struct {
	Kind     string                       `json:"kind"`
	Name     string                       `json:"name"`
	Help     TextRef                      `json:"help,omitzero"`     // kind: record, variant, enum
	Params   []Param                      `json:"params,omitzero"`   // kind: record, typeFunction
	Fields   []Field                      `json:"fields,omitzero"`   // kind: record
	Methods  []Method                     `json:"methods,omitzero"`  // kind: record
	Tag      string                       `json:"tag,omitzero"`      // kind: variant
	Cases    []Case                       `json:"cases,omitzero"`    // kind: variant
	Ordered  bool                         `json:"ordered,omitzero"`  // kind: enum
	Codes    string                       `json:"codes,omitzero"`    // kind: enum
	Members  []Member                     `json:"members,omitzero"`  // kind: enum
	Select   *string                      `json:"select,omitzero"`   // kind: typeFunction
	Branches []Branch                     `json:"branches,omitzero"` // kind: typeFunction
	Drivers  map[string]map[string]string `json:"drivers,omitzero"`  // kind: typeFunction
}

// Param is the object of TypeDef.params.
type Param struct {
	Name string   `json:"name"`
	Type TypeExpr `json:"type"`
}

// TypeExpr is #/$defs/typeExpr of spec/viewmodel.schema.json, its 18 branches in one struct.
type TypeExpr struct {
	Kind         string            `json:"kind"`
	Bits         int               `json:"bits,omitzero"`         // kind: int, float
	Signed       *bool             `json:"signed,omitzero"`       // kind: int
	MinLen       *int              `json:"minLen,omitzero"`       // kind: string
	MaxLen       *int              `json:"maxLen,omitzero"`       // kind: string
	Pattern      *string           `json:"pattern,omitzero"`      // kind: string
	Ref          string            `json:"ref,omitzero"`          // kind: enum, record, variant
	Bind         map[string]Driver `json:"bind,omitzero"`         // kind: record
	Of           *TypeExpr         `json:"of,omitzero"`           // kind: list, table, optional, union
	Stable       bool              `json:"stable,omitzero"`       // kind: table
	Key          *TypeExpr         `json:"key,omitzero"`          // kind: map
	Value        *TypeExpr         `json:"value,omitzero"`        // kind: map
	Min          Number            `json:"min,omitzero"`          // kind: int, float, duration, list, map
	Max          Number            `json:"max,omitzero"`          // kind: int, float, duration, list, map
	MinExclusive bool              `json:"minExclusive,omitzero"` // kind: float
	MaxExclusive bool              `json:"maxExclusive,omitzero"` // kind: float
	KeyedBy      string            `json:"keyedBy,omitzero"`      // kind: list
	Unique       bool              `json:"unique,omitzero"`       // kind: list
	Dependent    bool              `json:"dependent,omitzero"`    // kind: map
	Collection   string            `json:"collection,omitzero"`   // kind: ref
	Sibling      *Sibling          `json:"sibling,omitzero"`      // kind: ref
	Element      string            `json:"element,omitzero"`      // kind: ref
	KeyType      string            `json:"keyType,omitzero"`      // kind: ref
	Count        *int              `json:"count,omitzero"`        // kind: ref
	Active       *int              `json:"active,omitzero"`       // kind: ref
	Literals     []string          `json:"literals,omitzero"`     // kind: union
	Root         string            `json:"root,omitzero"`         // kind: asset
	Ext          []string          `json:"ext,omitzero"`          // kind: asset
	Fn           string            `json:"fn,omitzero"`           // kind: dependent
	On           *Driver           `json:"on,omitzero"`           // kind: dependent
	Predicate    *string           `json:"predicate,omitzero"`
}

// Driver is #/$defs/driver of spec/viewmodel.schema.json, its 3 branches in one struct.
type Driver struct {
	Field string `json:"field,omitzero"`
	Param string `json:"param,omitzero"`
	Key   bool   `json:"key,omitzero"`
}

// Sibling is #/$defs/sibling of spec/viewmodel.schema.json.
type Sibling struct {
	Up    int    `json:"up"`
	Field string `json:"field"`
}

// Field is #/$defs/field of spec/viewmodel.schema.json.
type Field struct {
	Name       string          `json:"name"`
	Type       TypeExpr        `json:"type"`
	Required   bool            `json:"required,omitzero"`
	Default    json.RawMessage `json:"default,omitzero"`
	Help       TextRef         `json:"help,omitzero"`
	Deprecated TextRef         `json:"deprecated,omitzero"`
	Wire       Wire            `json:"wire"`
	Stable     bool            `json:"stable,omitzero"`
	Input      *FieldInput     `json:"input,omitzero"`
}

// Wire is #/$defs/wire of spec/viewmodel.schema.json.
type Wire struct {
	Name   string          `json:"name"`
	Path   string          `json:"path,omitzero"`
	Unit   string          `json:"unit,omitzero"`
	None   json.RawMessage `json:"none,omitzero"`
	Inline bool            `json:"inline,omitzero"`
	Int    bool            `json:"int,omitzero"`
	Bits   bool            `json:"bits,omitzero"`
	Pairs  *WirePairs      `json:"pairs,omitzero"`
}

// WirePairs is the object of Wire.pairs.
type WirePairs struct {
	Keys  []string `json:"keys"`
	Slots int      `json:"slots"`
}

// FieldInput is the object of Field.input.
type FieldInput struct {
	Env string `json:"env"`
}

// Method is the object of TypeDef.methods.
type Method struct {
	Name    string   `json:"name"`
	Returns TypeExpr `json:"returns"`
}

// Case is the object of TypeDef.cases.
type Case struct {
	Name    string   `json:"name"`
	Wire    string   `json:"wire"`
	Retired bool     `json:"retired,omitzero"`
	Label   TextRef  `json:"label"`
	Help    TextRef  `json:"help,omitzero"`
	Icon    string   `json:"icon,omitzero"`
	Tone    string   `json:"tone,omitzero"`
	Fields  []Field  `json:"fields"`
	Methods []Method `json:"methods,omitzero"`
}

// Member is the object of TypeDef.members.
type Member struct {
	Name    string  `json:"name"`
	Wire    Scalar  `json:"wire"`
	Index   int     `json:"index"`
	Code    *int    `json:"code,omitzero"`
	Retired bool    `json:"retired,omitzero"`
	Label   TextRef `json:"label"`
	Help    TextRef `json:"help,omitzero"`
	Icon    string  `json:"icon,omitzero"`
	Tone    string  `json:"tone,omitzero"`
}

// Branch is the object of TypeDef.branches.
type Branch struct {
	Match []string `json:"match"`
	Type  TypeExpr `json:"type"`
}

// View is #/$defs/view of spec/viewmodel.schema.json, its 2 branches in one struct.
type View struct {
	Kind     string                `json:"kind"`
	Declared bool                  `json:"declared,omitzero"`
	Title    *Template             `json:"title,omitzero"`
	Subtitle *Template             `json:"subtitle,omitzero"`
	Preview  *Preview              `json:"preview,omitzero"`
	Singular TextRef               `json:"singular,omitzero"`
	Plural   TextRef               `json:"plural,omitzero"`
	Menu     *MenuRef              `json:"menu,omitzero"`
	Sections []Section             `json:"sections,omitzero"` // kind: record, case
	Fields   map[string]FieldView  `json:"fields,omitzero"`   // kind: record, case
	Methods  map[string]MethodView `json:"methods,omitzero"`  // kind: record, case
	Shows    map[string]ShowView   `json:"shows,omitzero"`    // kind: record, case
	Selector *Control              `json:"selector,omitzero"` // kind: variant
	Cases    map[string]View       `json:"cases,omitzero"`    // kind: variant; #/$defs/recordView only
}

// Template is #/$defs/template of spec/viewmodel.schema.json.
type Template struct {
	Template string  `json:"template"`
	Text     TextRef `json:"text,omitzero"`
}

// Preview is the object of View.preview.
type Preview struct {
	Expr string   `json:"expr"`
	Root string   `json:"root"`
	Ext  []string `json:"ext"`
}

// MenuRef is #/$defs/menuRef of spec/viewmodel.schema.json.
type MenuRef struct {
	Menu string `json:"menu"`
	Icon string `json:"icon,omitzero"`
}

// Section is #/$defs/section of spec/viewmodel.schema.json, its 4 branches in one struct.
type Section struct {
	Kind     string   `json:"kind"`
	ID       string   `json:"id,omitzero"`       // kind: group
	Label    TextRef  `json:"label,omitzero"`    // kind: group
	Intro    TextRef  `json:"intro,omitzero"`    // kind: group
	Advanced bool     `json:"advanced,omitzero"` // kind: group
	When     *string  `json:"when,omitzero"`     // kind: group
	Flatten  bool     `json:"flatten,omitzero"`  // kind: group
	Entries  []Entry  `json:"entries,omitzero"`  // kind: group, other
	Fields   []string `json:"fields,omitzero"`   // kind: other, unused
}

// Entry is the object of Section.entries.
type Entry struct {
	Field  string `json:"field,omitzero"`
	Method string `json:"method,omitzero"`
	Show   string `json:"show,omitzero"`
}

// FieldView is #/$defs/fieldView of spec/viewmodel.schema.json.
type FieldView struct {
	Label       TextRef         `json:"label"`
	Help        TextRef         `json:"help,omitzero"`
	Control     Control         `json:"control"`
	Readonly    string          `json:"readonly,omitzero"`
	Single      json.RawMessage `json:"single,omitzero"`
	Hidden      bool            `json:"hidden,omitzero"`
	When        *string         `json:"when,omitzero"`
	Placeholder TextRef         `json:"placeholder,omitzero"`
	None        TextRef         `json:"none,omitzero"`
	Step        TextRef         `json:"step,omitzero"`
	Case        string          `json:"case,omitzero"`
	Path        string          `json:"path,omitzero"`
	Env         string          `json:"env,omitzero"`
}

// Control is #/$defs/control of spec/viewmodel.schema.json.
type Control struct {
	Kind         string           `json:"kind"`
	Source       *Source          `json:"source,omitzero"`
	Pinned       []string         `json:"pinned,omitzero"`
	Optional     *ControlOptional `json:"optional,omitzero"`
	Min          Number           `json:"min,omitzero"`
	Max          Number           `json:"max,omitzero"`
	MinExclusive bool             `json:"minExclusive,omitzero"`
	MaxExclusive bool             `json:"maxExclusive,omitzero"`
	Stepper      bool             `json:"stepper,omitzero"`
	Unit         string           `json:"unit,omitzero"`
	Units        []string         `json:"units,omitzero"`
	MinLen       *int             `json:"minLen,omitzero"`
	MaxLen       *int             `json:"maxLen,omitzero"`
	Pattern      *string          `json:"pattern,omitzero"`
	Root         string           `json:"root,omitzero"`
	Ext          []string         `json:"ext,omitzero"`
	Of           string           `json:"of,omitzero"`
	Element      *Control         `json:"element,omitzero"`
	Count        int              `json:"count,omitzero"`
	MinCount     *int             `json:"minCount,omitzero"`
	Strict       bool             `json:"strict,omitzero"`
	Key          string           `json:"key,omitzero"`
	Orderable    bool             `json:"orderable,omitzero"`
	Columns      []Column         `json:"columns,omitzero"`
	Filters      []Filter         `json:"filters,omitzero"`
	Search       string           `json:"search,omitzero"`
	Singular     TextRef          `json:"singular,omitzero"`
	KeyControl   *Control         `json:"keyControl,omitzero"`
	Value        *Control         `json:"value,omitzero"`
	KeyFixed     bool             `json:"keyFixed,omitzero"`
	Inline       bool             `json:"inline,omitzero"`
	Selector     *Control         `json:"selector,omitzero"`
	Fn           string           `json:"fn,omitzero"`
	On           *Driver          `json:"on,omitzero"`
	Branches     []Control        `json:"branches,omitzero"`
	Widget       string           `json:"widget,omitzero"`
	Siblings     bool             `json:"siblings,omitzero"`
	Fallback     *Control         `json:"fallback,omitzero"`
}

// Source is the object of Control.source.
type Source struct {
	Bool       bool     `json:"bool,omitzero"`
	Enum       string   `json:"enum,omitzero"`
	Cases      string   `json:"cases,omitzero"`
	Collection string   `json:"collection,omitzero"`
	Sibling    *Sibling `json:"sibling,omitzero"`
}

// ControlOptional is the object of Control.optional.
type ControlOptional struct {
	Unset      string `json:"unset"`
	ThreeState bool   `json:"threeState,omitzero"`
}

// Column is the object of Control.columns.
type Column struct {
	Field string   `json:"field"`
	Width int      `json:"width,omitzero"`
	Mode  string   `json:"mode"`
	Cell  *Control `json:"cell,omitzero"`
}

// Filter is the object of Control.filters.
type Filter struct {
	Field   string  `json:"field"`
	Kind    string  `json:"kind"`
	Multi   bool    `json:"multi,omitzero"`
	None    bool    `json:"none,omitzero"`
	Control Control `json:"control"`
}

// MethodView is the object of View.methods.
type MethodView struct {
	Label  TextRef `json:"label"`
	Help   TextRef `json:"help,omitzero"`
	Hidden bool    `json:"hidden,omitzero"`
	When   *string `json:"when,omitzero"`
}

// ShowView is the object of View.shows.
type ShowView struct {
	Label TextRef  `json:"label"`
	Text  Template `json:"text"`
}

// Value is #/$defs/value of spec/viewmodel.schema.json.
type Value struct {
	Name     string   `json:"name"`
	Order    int      `json:"order"`
	Type     TypeExpr `json:"type"`
	Label    TextRef  `json:"label"`
	Help     TextRef  `json:"help,omitzero"`
	Menu     *MenuRef `json:"menu,omitzero"`
	Control  Control  `json:"control"`
	Editable string   `json:"editable"`
	Reason   string   `json:"reason,omitzero"`
	Reload   bool     `json:"reload,omitzero"`
	Layers   []string `json:"layers,omitzero"`
	Failed   bool     `json:"failed,omitzero"`
	Sources  Sources  `json:"sources"`
}

// Sources is the object of Value.sources.
type Sources struct {
	Files   []string `json:"files"`
	Glob    string   `json:"glob,omitzero"`
	Count   *int     `json:"count,omitzero"`
	Entries *int     `json:"entries,omitzero"`
}

// Usage is #/$defs/usage of spec/viewmodel.schema.json.
type Usage struct {
	Shapes map[string]Shape `json:"shapes"`
}

// Shape is the object of Usage.shapes.
type Shape struct {
	Count  int            `json:"count"`
	Fields map[string]int `json:"fields"`
	Main   []string       `json:"main"`
	More   []string       `json:"more,omitzero"`
}

// SearchIndex is #/$defs/searchIndex of spec/viewmodel.schema.json.
type SearchIndex struct {
	Type    string         `json:"type"`
	KeyType string         `json:"keyType"`
	Count   int            `json:"count"`
	Active  int            `json:"active"`
	Preview *SearchPreview `json:"preview,omitzero"`
	Rows    []Row          `json:"rows"`
}

// SearchPreview is the object of SearchIndex.preview.
type SearchPreview struct {
	Root string   `json:"root"`
	Ext  []string `json:"ext"`
}

// Row is the object of SearchIndex.rows.
type Row struct {
	Key      Scalar             `json:"key"`
	Title    *string            `json:"title,omitzero"`
	Subtitle *string            `json:"subtitle,omitzero"`
	Terms    []string           `json:"terms,omitzero"`
	Preview  string             `json:"preview,omitzero"`
	Retired  bool               `json:"retired,omitzero"`
	Tr       map[string]RowText `json:"tr,omitzero"`
}

// RowText is the object of Row.tr.
type RowText struct {
	Title    *string `json:"title,omitzero"`
	Subtitle *string `json:"subtitle,omitzero"`
}

// Asset is the object of ViewModel.assets.
type Asset struct {
	Dir string `json:"dir"`
}

// Unit is #/$defs/unit of spec/viewmodel.schema.json.
type Unit struct {
	Suffix    TextRef `json:"suffix,omitzero"`
	Scale     Number  `json:"scale"`
	Thousands bool    `json:"thousands"`
	Decimals  int     `json:"decimals"`
}

// Widget is #/$defs/widget of spec/viewmodel.schema.json.
type Widget struct {
	Value    TypeExpr  `json:"value"`
	Siblings *TypeExpr `json:"siblings,omitzero"`
	Default  bool      `json:"default,omitzero"`
	Help     *string   `json:"help,omitzero"`
}

// Studio is #/$defs/studio of spec/viewmodel.schema.json.
type Studio struct {
	Menus   string            `json:"menus"`
	Icons   []string          `json:"icons"`
	Tones   []string          `json:"tones"`
	Units   map[string]Unit   `json:"units"`
	Widgets map[string]Widget `json:"widgets"`
}

// I18N is #/$defs/i18n of spec/viewmodel.schema.json.
type I18N struct {
	Source    string              `json:"source"`
	Languages map[string]Language `json:"languages"`
}

// Language is the object of I18N.languages.
type Language struct {
	Files   []string          `json:"files,omitzero"`
	Missing *int              `json:"missing,omitzero"`
	Texts   map[string]string `json:"texts"`
}

// Finding is #/$defs/finding of spec/viewmodel.schema.json.
type Finding struct {
	Severity   string            `json:"severity"`
	Code       string            `json:"code"`
	File       string            `json:"file,omitzero"`
	Line       int               `json:"line,omitzero"`
	Col        int               `json:"col,omitzero"`
	EndLine    int               `json:"endLine,omitzero"`
	EndCol     int               `json:"endCol,omitzero"`
	Pointer    *string           `json:"pointer,omitzero"`
	Package    string            `json:"package"`
	Path       string            `json:"path,omitzero"`
	Message    string            `json:"message"`
	Check      string            `json:"check,omitzero"`
	Layer      string            `json:"layer,omitzero"`
	Related    []Related         `json:"related,omitzero"`
	Stack      []Frame           `json:"stack,omitzero"`
	MoreFrames int               `json:"moreFrames,omitzero"`
	Reads      []string          `json:"reads,omitzero"`
	Messages   map[string]string `json:"messages,omitzero"`
}

// Related is the object of Finding.related.
type Related struct {
	File    string `json:"file"`
	Line    int    `json:"line"`
	Col     int    `json:"col"`
	EndLine int    `json:"endLine"`
	EndCol  int    `json:"endCol"`
	Note    string `json:"note"`
}

// Frame is the object of Finding.stack.
type Frame struct {
	Fn      string `json:"fn"`
	File    string `json:"file"`
	Line    int    `json:"line"`
	Col     int    `json:"col"`
	EndLine int    `json:"endLine"`
	EndCol  int    `json:"endCol"`
}
